/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6240fdfb-fdd0-4b30-84a6-e541e8e0eb3e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

/-
**Lemma 3.5** `lem:Phi-upper-bound`
Φ_Δ(a₁, a₂) is essentially upper bounded in terms of a₁a₂.

**Claim 3.6**
f has a unique zero ξ on (1,∞).

**Proposition 3.7** `prop:basic-ineq-2`
-/


import MultivarIndepFormalize.Definitions

set_option linter.style.longLine false

open Real

noncomputable section

/--
The polynomial f(X) = (Δ+1)sX^{2Δ} - ΔX^{Δ+1} - 1.
Used in Claim 3.6 to define the unique zero ξ_Δ(s).
-/
def f_poly (Δ : ℕ) (s : ℝ) (X : ℝ) : ℝ :=
  (Δ + 1 : ℝ) * s * X ^ (2 * (Δ : ℝ)) - (Δ : ℝ) * X ^ ((Δ : ℝ) + 1) - 1

/-
**Claim 3.6**
f has a unique zero ξ on (1,∞).

**Statement**
For \(0< s<1\), $f(X)$ has a unique zero \(\xi_\Delta (s)\) on \((1,\infty)\).

f(X) is f_poly and defined as (Δ+1)a_1a_2 X^{2Δ} - Δ X^{Δ+1} - 1
-/
noncomputable section AristotleLemmas

/-
Auxiliary function h(X) = (Δ+1)s X^{Δ-1} - X^{-(Δ+1)}. Used to transform the equation f(X)=0 into h(X)=Δ.
-/
def h_aux (Δ : ℕ) (s : ℝ) (X : ℝ) : ℝ :=
  (Δ + 1 : ℝ) * s * X ^ ((Δ : ℝ) - 1) - 1 / X ^ ((Δ : ℝ) + 1)

/-
Equivalence between f(X)=0 and h(X)=Δ for X > 0.
Proof: Divide f(X)=0 by X^(Δ+1) and rearrange terms.
-/
lemma f_poly_eq_h_aux_iff (Δ : ℕ) (s X : ℝ) (hX : 0 < X) :
    f_poly Δ s X = 0 ↔ h_aux Δ s X = Δ := by
      unfold f_poly h_aux;
      rw [ sub_div', div_eq_iff ] <;> first | positivity | ring;
      norm_num [ Real.rpow_add hX, Real.rpow_neg_one ] ; ring;
      norm_cast ; simp +decide [ sq, mul_assoc, mul_comm, mul_left_comm, hX.ne' ];
      constructor <;> intro h <;> linear_combination h

/-
h(X) is strictly increasing on (0, ∞) because it is the difference of an increasing function and a decreasing function (or sum of two increasing functions).
The first term (Δ+1)s X^(Δ-1) is increasing because Δ ≥ 2 implies Δ-1 > 0.
The second term -1/X^(Δ+1) is increasing because 1/X^(Δ+1) is decreasing (exponent Δ+1 > 0).
-/
lemma h_aux_strict_mono (Δ : ℕ) (hΔ : 2 ≤ Δ) (s : ℝ) (hs : 0 < s) :
    StrictMonoOn (h_aux Δ s) (Set.Ioi 0) := by
      intro x hx y hy hxy;
      rcases Δ with ( _ | _ | Δ ) <;> norm_num [ h_aux ] at *;
      gcongr

/-
h(1) < Δ given s < 1.
Proof: h(1) = (Δ+1)s - 1. Since s < 1, (Δ+1)s < Δ+1, so (Δ+1)s - 1 < Δ.
-/
lemma h_aux_one_lt_Delta (Δ : ℕ) (s : ℝ) (hs : s < 1) :
    h_aux Δ s 1 < Δ := by
      unfold h_aux;
      rcases Δ with ( _ | _ | Δ ) <;> norm_num at *
      · linarith
      · linarith
      · nlinarith

/-
Limit of h(X) as X -> infinity is infinity.
Proof: The first term tends to infinity because the exponent is positive. The second term tends to 0.
-/
lemma h_aux_tendsto_atTop (Δ : ℕ) (hΔ : 2 ≤ Δ) (s : ℝ) (hs : 0 < s) :
    Filter.Tendsto (h_aux Δ s) Filter.atTop Filter.atTop := by
      -- The first term $(Δ+1)s X^{Δ-1}$ tends to infinity as $X$ tends to infinity because $Δ-1 > 0$ and $s > 0$.
      have h_term1 : Filter.Tendsto (fun X : ℝ => (Δ + 1 : ℝ) * s * X ^ ((Δ : ℝ) - 1)) Filter.atTop Filter.atTop := by
        exact Filter.Tendsto.const_mul_atTop ( by positivity ) ( tendsto_rpow_atTop ( by norm_num; linarith ) );
      -- The second term $-1/X^{Δ+1}$ tends to 0 as $X$ tends to infinity because $Δ+1 > 0$.
      have h_term2 : Filter.Tendsto (fun X : ℝ => -1 / X ^ ((Δ : ℝ) + 1)) Filter.atTop (nhds 0) := by
        exact tendsto_const_nhds.div_atTop ( tendsto_rpow_atTop ( by positivity ) );
      convert h_term1.atTop_add h_term2 using 1 ; ring;
      ext; unfold h_aux; ring

end AristotleLemmas

lemma xi_unique_zero (Δ : ℕ) (hΔ : Δ ≥ 2) (s : ℝ) (hs₀ : 0 < s) (hs₁ : s < 1) :
    ∃! X : ℝ, X > 1 ∧ f_poly Δ s X = 0 := by
  -- By `f_poly_eq_h_aux_iff`, for X > 0, f_poly(X) = 0 is equivalent to h_aux(X) = Δ.
  have h_unique : ∃! X : ℝ, X > 1 ∧ h_aux Δ s X = Δ := by
    -- By `h_aux_strict_mono`, there exists a unique $X \in (1, \infty)$ such that $h_aux Δ s X = Δ$.
    obtain ⟨X, hX⟩ : ∃ X : ℝ, X > 1 ∧ h_aux Δ s X = Δ := by
      -- By the Intermediate Value Theorem, since $h(1) < \Delta$ and $h(X) \to \infty$ as $X \to \infty$, there exists some $b > 1$ such that $h(b) > \Delta$.
      obtain ⟨b, hb₁, hb₂⟩ : ∃ b > 1, h_aux Δ s b > Δ := by
        have := h_aux_tendsto_atTop Δ hΔ s hs₀;
        exact Filter.eventually_atTop.mp ( this.eventually_gt_atTop ( Δ : ℝ ) ) |> fun ⟨ b, hb ⟩ ↦ ⟨ Max.max b 2, by norm_num, hb _ ( le_max_left _ _ ) ⟩;
      -- By the Intermediate Value Theorem, since $h(1) < \Delta$ and $h(X) \to \infty$ as $X \to \infty$, there exists some $c \in (1, b)$ such that $h(c) = \Delta$.
      obtain ⟨c, hc₁, hc₂⟩ : ∃ c ∈ Set.Ioo 1 b, h_aux Δ s c = Δ := by
        apply_rules [ intermediate_value_Ioo ];
        · linarith;
        · exact continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.sub ( ContinuousAt.mul continuousAt_const <| ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl <| by linarith [ hx.1 ] ) <| ContinuousAt.div continuousAt_const ( ContinuousAt.rpow continuousAt_id continuousAt_const <| Or.inl <| by linarith [ hx.1 ] ) <| ne_of_gt <| Real.rpow_pos_of_pos ( by linarith [ hx.1 ] ) _;
        · exact ⟨ h_aux_one_lt_Delta Δ s hs₁, hb₂ ⟩;
      exact ⟨ c, hc₁.1, hc₂ ⟩;
    refine' ⟨ X, hX, fun Y hY => _ ⟩;
    exact StrictMonoOn.injOn ( h_aux_strict_mono Δ hΔ s hs₀ ) ( show 0 < Y by linarith [ hY.1 ] ) ( show 0 < X by linarith [ hX.1 ] ) <| by linarith [ hY.2, hX.2 ] ;
  convert h_unique using 2;
  exact ⟨ fun h => ⟨ h.1, by rw [ f_poly_eq_h_aux_iff Δ s _ ( by linarith ) ] at h; exact h.2 ⟩, fun h => ⟨ h.1, by rw [ f_poly_eq_h_aux_iff Δ s _ ( by linarith ) ] ; exact h.2 ⟩ ⟩

/--
The unique zero ξ_Δ(s) of f(X) = (Δ+1)sX^{2Δ} - ΔX^{Δ+1} - 1 on (1, ∞).
-/
def xi_Δ (Δ : ℕ) (hΔ : Δ ≥ 2) (s : ℝ) (hs₀ : 0 < s) (hs₁ : s < 1) : ℝ :=
  (xi_unique_zero Δ hΔ s hs₀ hs₁).choose

/--
The auxiliary function Ψ_Δ(s) = ξ_Δ(s) - (2/Δ) * s * ξ_Δ(s)^Δ.
Matches source definition.
-/
def Psi_Delta (Δ : ℕ) (hΔ : Δ ≥ 2) (s : ℝ) (hs₀ : 0 < s) (hs₁ : s < 1) : ℝ :=
  let ξ := xi_Δ Δ hΔ s hs₀ hs₁
  ξ - (2 / (Δ : ℝ)) * s * ξ ^ (Δ : ℝ)

/- Aristotle failed to find a proof. -/
/--
**Lemma 3.5** `lem:Phi-upper-bound`
Φ_Δ(a₁, a₂) is essentially upper bounded in terms of a₁a₂.

Statement:
There is a function \(\Psi_\Delta\colon(0,1)\to\RR\) such that
for all \(a_1,a_2>0\) with \(a_1a_2<1\),
\[
    \Phi_\Delta(a_1,a_2) \le \Psi_\Delta(a_1a_2) + (a_1+a_2)/\Delta.
\]
Moreover, if \(a_1=a_2\), then equality holds.

Ψ_Δ is explicitly defined in Psi_Delta.
-/
lemma Phi_upper_bound (Δ : ℕ) (hΔ : Δ ≥ 2) (a₁ a₂ : ℝ)
    (ha₁ : a₁ > 0) (ha₂ : a₂ > 0) (h_prod : a₁ * a₂ < 1) :
    let s := a₁ * a₂
    let hs₀ : 0 < s := by simpa [s] using (mul_pos ha₁ ha₂)
    let hs₁ : s < 1 := by simpa [s] using h_prod
    let Ψ_Δ := Psi_Delta Δ hΔ
    let Ψ_Δ_s := Ψ_Δ s hs₀ hs₁
    Φ_Δ Δ a₁ a₂ ≤ Ψ_Δ_s + (a₁ + a₂) / (Δ : ℝ) ∧
    (a₁ = a₂ → Φ_Δ Δ a₁ a₂ = Ψ_Δ_s + (a₁ + a₂) / (Δ : ℝ)) := by
  sorry

/--
**Proposition 3.7** `prop:basic-ineq`

**Statement**
Let \(d\ge1\) and \(x,y\ge0\). Then
\(
  (dx+1)^{d+1} (dy+1)^{d+1} \le \bigl( (d+1)dxy + (d+1)(x+y) + 1 \bigr)^{2d}
\).
Equality holds if and only if \(x=y=0\).
-/
lemma basic_ineq (d : ℕ) (hd : d ≥ 1) (x y : ℝ) (hx : x ≥ 0) (hy : y ≥ 0) :
    ((d : ℝ) * x + 1) ^ ((d : ℝ) + 1) * ((d : ℝ) * y + 1) ^ ((d : ℝ) + 1) ≤
    ((d + 1 : ℝ) * d * x * y + (d + 1 : ℝ) * (x + y) + 1) ^ (2 * (d : ℝ)) ∧
    (((d : ℝ) * x + 1) ^ ((d : ℝ) + 1) * ((d : ℝ) * y + 1) ^ ((d : ℝ) + 1) =
    ((d + 1 : ℝ) * d * x * y + (d + 1 : ℝ) * (x + y) + 1) ^ (2 * (d : ℝ)) ↔ x = 0 ∧ y = 0) := by
  constructor;
  · norm_cast ; norm_num [ mul_pow ];
    rw [ ← mul_pow ];
    refine' le_trans ( pow_le_pow_left₀ ( by positivity ) ( show ( ( d : ℝ ) * x + 1 ) * ( ( d : ℝ ) * y + 1 ) ≤ ( ( d + 1 ) * ( d : ℝ ) * x * y + ( d + 1 ) * ( x + y ) + 1 ) by nlinarith [ mul_nonneg hx hy, mul_nonneg hx ( sq_nonneg y ), mul_nonneg hy ( sq_nonneg x ) ] ) _ ) _;
    exact pow_le_pow_right₀ ( by nlinarith [ mul_nonneg hx hy, mul_nonneg ( Nat.cast_nonneg d ) hx, mul_nonneg ( Nat.cast_nonneg d ) hy ] ) ( by linarith );
  · constructor;
    · contrapose!;
      -- Assume $x \neq 0$ or $y \neq 0$. Without loss of generality, assume $x \neq 0$.
      intro hxy
      by_cases hx0 : x = 0;
      · rcases d with ( _ | _ | d ) <;> simp_all +decide;
        · norm_num; nlinarith [ mul_self_pos.2 hxy ];
        · norm_cast;
          refine' ne_of_lt ( lt_of_lt_of_le _ ( pow_le_pow_right₀ ( by nlinarith [ show ( 0 : ℝ ) < y by positivity ] ) ( show 2 * ( d + 1 + 1 ) ≥ d + 1 + 1 + 1 by linarith ) ) );
          gcongr ; norm_num;
      · by_cases hy0 : y = 0 <;> simp_all +decide [ Real.rpow_add, Real.rpow_mul ];
        · norm_cast ; norm_num [ pow_mul' ];
          rw [ ← pow_mul' ];
          refine' ne_of_lt ( lt_of_lt_of_le _ ( pow_le_pow_right₀ ( by nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast ] ) ( show d + 1 ≤ 2 * d by linarith ) ) );
          gcongr ; nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, show x > 0 by positivity ];
        · -- By simplifying, we can see that the inequality holds strictly for $x, y > 0$.
          have h_simp : ((d * x + 1) * (d * y + 1)) ^ (d + 1 : ℝ) < (((d + 1) * d * x * y + (d + 1) * (x + y) + 1) ^ (2 * d : ℝ)) := by
            field_simp;
            -- By simplifying, we can see that the inequality holds strictly for $x, y > 0$ because the right-hand side grows faster than the left-hand side.
            have h_simp : ((d * x + 1) * (d * y + 1)) < ((d + 1) * (d * x * y + (x + y)) + 1) := by
              nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, show 0 < x * y by positivity, show 0 < x by positivity, show 0 < y by positivity, mul_le_mul_of_nonneg_left ( show ( d : ℝ ) ≥ 1 by norm_cast ) hx, mul_le_mul_of_nonneg_left ( show ( d : ℝ ) ≥ 1 by norm_cast ) hy ];
            exact lt_of_lt_of_le ( Real.rpow_lt_rpow ( by positivity ) h_simp ( by positivity ) ) ( Real.rpow_le_rpow_of_exponent_le ( by nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, mul_nonneg hx hy ] ) ( by norm_cast; linarith ) );
          rw [ ← Real.mul_rpow ( by positivity ) ( by positivity ) ] ; exact ne_of_lt h_simp;
    · aesop


/-
Algebraic inequality related to the Hessian of A_d.
-/
lemma Ad_hessian_ineq (d : ℕ) (hd : d ≥ 1) (x y u w : ℝ) (hA : A_d (d + 1) x y > 0) :
    2 * A_d (d + 1) x y * u * w ≤ ((d * y + 1) * u + (d * x + 1) * w) ^ 2 := by
      unfold A_d at *;
      -- We can divide both sides by $(d^2xy + dx + dy + 1)$ since it is positive.
      have h_div : (d * x + 1) * (d * y + 1) ≥ d * x * y + x + y := by
        cases le_total x 0 <;> cases le_total y 0 <;> push_cast at * <;> nlinarith [ ( by norm_cast : ( 1 : ℝ ) ≤ d ), mul_nonneg ( Nat.cast_nonneg d ) ( sq_nonneg x ), mul_nonneg ( Nat.cast_nonneg d ) ( sq_nonneg y ) ];
      norm_num at *;
      nlinarith [ sq_nonneg ( ( d * y + 1 ) * u - ( d * x + 1 ) * w ) ]

/-
The function $t \mapsto A_{d+1}(x_0+tu, y_0+tw)^{1/(d+1)}$ is concave on any interval where $A_{d+1} > 0$.
-/
lemma Ad_line_concave (d : ℕ) (hd : d ≥ 1) (x0 y0 u w : ℝ) (I : Set ℝ) (hI : Convex ℝ I)
    (h_pos : ∀ t ∈ I, A_d (d + 1) (x0 + t * u) (y0 + t * w) > 0) :
    ConcaveOn ℝ I (fun t => (A_d (d + 1) (x0 + t * u) (y0 + t * w)) ^ (1 / ((d : ℝ) + 1))) := by
      apply_rules [ concaveOn_of_deriv2_nonpos, neg_nonneg ];
      · refine' ContinuousOn.rpow ( Continuous.continuousOn _ ) continuousOn_const _;
        · unfold A_d; continuity;
        · exact fun t ht => Or.inl <| ne_of_gt <| h_pos t ht;
      · refine' DifferentiableOn.rpow _ _ _;
        · unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_comm w ] ;
          fun_prop;
        · exact differentiableOn_const _;
        · exact fun t ht => ne_of_gt <| h_pos t <| interior_subset ht;
      · -- The derivative of $A_d(x_0 + tu, y_0 + tw)^{1/(d+1)}$ is given by the chain rule.
        have h_deriv : ∀ t ∈ I, deriv (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w) ^ (1 / (d + 1 : ℝ))) t = (1 / (d + 1 : ℝ)) * A_d (d + 1) (x0 + t * u) (y0 + t * w) ^ ((1 / (d + 1 : ℝ)) - 1) * (deriv (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w)) t) := by
          intro t ht;
          convert HasDerivAt.deriv ( HasDerivAt.rpow_const ( hasDerivAt_deriv_iff.mpr _ ) _ ) using 1 <;> norm_num;
          · ring;
          · unfold A_d; norm_num;
          · exact Or.inl <| ne_of_gt <| h_pos t ht;
        refine' DifferentiableOn.congr _ fun t ht => h_deriv t ( interior_subset ht );
        refine' DifferentiableOn.mul ( DifferentiableOn.mul ( differentiableOn_const _ ) _ ) _;
        · refine' DifferentiableOn.rpow _ _ _ <;> norm_num;
          · unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_comm w ] ;
            fun_prop;
          · exact fun t ht => ne_of_gt <| h_pos t <| interior_subset ht;
        · unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_comm w ] ;
          exact Differentiable.differentiableOn ( by rw [ show deriv ( fun y => ( d + 1 : ℝ ) * ( d * ( ( x0 + y * u ) * ( y0 + y * w ) ) ) + ( d + 1 : ℝ ) * ( x0 + y * u + ( y0 + y * w ) ) ) = fun y => deriv ( fun y => ( d + 1 : ℝ ) * ( d * ( ( x0 + y * u ) * ( y0 + y * w ) ) ) + ( d + 1 : ℝ ) * ( x0 + y * u + ( y0 + y * w ) ) ) y from rfl ] ; norm_num [ mul_assoc, mul_comm u, mul_comm w ] );
      · -- By definition of $F$, we know that its second derivative is given by the expression we derived.
        intro t ht
        have h_deriv2 : deriv^[2] (fun t => (A_d (d + 1) (x0 + t * u) (y0 + t * w)) ^ (1 / (d + 1 : ℝ))) t =
          (1 / (d + 1 : ℝ)) * (A_d (d + 1) (x0 + t * u) (y0 + t * w)) ^ ((1 / (d + 1 : ℝ)) - 2) *
          ((-d / (d + 1 : ℝ)) * (deriv (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w)) t)^2 +
          (A_d (d + 1) (x0 + t * u) (y0 + t * w)) * deriv^[2] (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w)) t) := by
            convert HasDerivAt.deriv ( _ ) using 1;
            convert HasDerivAt.congr_of_eventuallyEq _ ?_ using 1;
            use fun t => ( 1 / ( d + 1 : ℝ ) ) * ( A_d ( d + 1 ) ( x0 + t * u ) ( y0 + t * w ) ) ^ ( 1 / ( d + 1 : ℝ ) - 1 ) * deriv ( fun t => A_d ( d + 1 ) ( x0 + t * u ) ( y0 + t * w ) ) t;
            · convert HasDerivAt.mul ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( HasDerivAt.rpow_const ( hasDerivAt_deriv_iff.mpr _ ) _ ) ) ( hasDerivAt_deriv_iff.mpr _ ) using 1 <;> norm_num;
              · rw [ show ( ( d : ℝ ) + 1 ) ⁻¹ - 1 = ( ( d : ℝ ) + 1 ) ⁻¹ - 2 + 1 by ring ] ; rw [ Real.rpow_add_one ( ne_of_gt ( h_pos t ( interior_subset ht ) ) ) ] ; ring;
                grind;
              · unfold A_d; norm_num [ mul_comm u, mul_comm w ] ;
              · exact Or.inl <| ne_of_gt <| h_pos t <| interior_subset ht;
              · unfold A_d; norm_num [ mul_comm u, mul_comm w ] ;
                unfold deriv ; norm_num [ fderiv_deriv, mul_comm u, mul_comm w ];
            · filter_upwards [ IsOpen.mem_nhds ( isOpen_interior ) ht ] with t ht;
              convert HasDerivAt.deriv ( HasDerivAt.rpow_const ( hasDerivAt_deriv_iff.mpr _ ) _ ) using 1 <;> norm_num;
              · ring;
              · unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_comm w ] ;
              · exact Or.inl <| ne_of_gt <| h_pos t <| interior_subset ht;
        -- Substitute the expressions for the first and second derivatives into the second derivative formula.
        have h_subst : deriv^[2] (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w)) t = (d + 1) * (d : ℝ) * u * w + (d + 1) * (d : ℝ) * u * w := by
          unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_left_comm w ] ;
          unfold deriv ; norm_num [ fderiv_deriv, mul_assoc, mul_comm u, mul_left_comm w ] ; ring;
        -- Substitute the expression for the second derivative into the inequality.
        have h_ineq : 2 * (A_d (d + 1) (x0 + t * u) (y0 + t * w)) * u * w ≤ ((d * (y0 + t * w) + 1) * u + (d * (x0 + t * u) + 1) * w) ^ 2 := by
          convert Ad_hessian_ineq d hd ( x0 + t * u ) ( y0 + t * w ) u w _ using 1 ; ring;
          simpa only [ add_comm ] using h_pos t ( interior_subset ht );
        -- Substitute the expression for the first derivative into the inequality.
        have h_deriv1 : deriv (fun t => A_d (d + 1) (x0 + t * u) (y0 + t * w)) t = (d + 1) * ((d : ℝ) * (y0 + t * w) + 1) * u + (d + 1) * ((d : ℝ) * (x0 + t * u) + 1) * w := by
          unfold A_d; norm_num [ mul_assoc, mul_comm u, mul_comm w ] ; ring;
        rw [ h_deriv2, h_deriv1, h_subst ];
        refine mul_nonpos_of_nonneg_of_nonpos ( mul_nonneg ( by positivity ) ( Real.rpow_nonneg ( le_of_lt ( h_pos t ( interior_subset ht ) ) ) _ ) ) ?_;
        field_simp;
        nlinarith [ show ( d : ℝ ) * ( d + 1 ) > 0 by positivity ]

/-
For \(d\ge2\), \(A_{d+1}(x,y)^{\frac{1}{d+1}}\) is concave on any convex subset of \(\{(x,y)\in\RR^2 : A_{d+1}(x,y)>0\}\).
-/
lemma Ad_concave (d : ℕ) (hd : d ≥ 2) (S : Set (ℝ × ℝ)) (hS_conv : Convex ℝ S)
    (hS_pos : ∀ p ∈ S, A_d (d + 1) p.1 p.2 > 0) :
    ConcaveOn ℝ S (fun p => (A_d (d + 1) p.1 p.2) ^ (1 / ((d : ℝ) + 1))) := by
      refine' ⟨ hS_conv, _ ⟩;
      intros p1 hp1 p2 hp2 a b ha hb hab;
      -- Apply the line concavity lemma with $x_0 = p1.1$, $y_0 = p1.2$, $u = p2.1 - p1.1$, $w = p2.2 - p1.2$, and $I = [0, 1]$.
      have h_line_concave : ConcaveOn ℝ (Set.Icc 0 1) (fun t : ℝ => (A_d (d + 1) (p1.1 + t * (p2.1 - p1.1)) (p1.2 + t * (p2.2 - p1.2))) ^ (1 / (d + 1) : ℝ)) := by
        apply_rules [ Ad_line_concave ];
        · linarith;
        · exact convex_Icc _ _;
        · intro t ht; convert hS_pos ( p1.1 + t * ( p2.1 - p1.1 ), p1.2 + t * ( p2.2 - p1.2 ) ) _ using 1;
          convert hS_conv hp1 hp2 ( by linarith [ ht.1, ht.2 ] : 0 ≤ 1 - t ) ( by linarith [ ht.1, ht.2 ] : 0 ≤ t ) ( by linarith [ ht.1, ht.2 ] ) using 1 ; ext <;> simp +decide [ mul_comm ];
          · ring;
          · ring;
      convert h_line_concave.2 ( show 0 ∈ Set.Icc 0 1 by norm_num ) ( show 1 ∈ Set.Icc 0 1 by norm_num ) ha hb hab using 1 <;> norm_num ; ring;
      grind

/-
Homogenization of A_{d+1}.
-/
def h_homog (d : ℕ) (w x y : ℝ) : ℝ :=
  (d + 1 : ℝ) * d * w ^ (d - 1) * x * y + (d + 1 : ℝ) * w ^ d * (x + y) + w ^ (d + 1)

/-
Relation between h_homog and A_d.
-/
lemma h_homog_eq_Ad (d : ℕ) (w x y : ℝ) (hw : w > 0) :
    h_homog d w x y = w ^ (d + 1) * A_d (d + 1) (x / w) (y / w) := by
      unfold h_homog A_d; ring;
      field_simp;
      cases d <;> norm_num [ pow_succ' ] ; ring;
      ring

/-
Log-convexity of h_homog.
-/
lemma h_homog_cauchy_schwarz (d : ℕ) (w1 x1 y1 w2 x2 y2 : ℝ)
    (hw1 : 0 ≤ w1) (hx1 : 0 ≤ x1) (hy1 : 0 ≤ y1)
    (hw2 : 0 ≤ w2) (hx2 : 0 ≤ x2) (hy2 : 0 ≤ y2) :
    (h_homog d (Real.sqrt (w1 * w2)) (Real.sqrt (x1 * x2)) (Real.sqrt (y1 * y2))) ^ 2 ≤
    h_homog d w1 x1 y1 * h_homog d w2 x2 y2 := by
      unfold h_homog;
      -- Apply the Cauchy-Schwarz inequality to the sums.
      have h_cauchy_schwarz : ∀ (a b c d e f g h : ℝ), 0 ≤ a → 0 ≤ b → 0 ≤ c → 0 ≤ d → 0 ≤ e → 0 ≤ f → 0 ≤ g → 0 ≤ h →
        (a * d + b * e + c * f + g * h) ^ 2 ≤
        (a ^ 2 + b ^ 2 + c ^ 2 + g ^ 2) *
        (d ^ 2 + e ^ 2 + f ^ 2 + h ^ 2) := by
          exact fun a b c d e f g h ha hb hc hd he hf hg hh => by linarith [ sq_nonneg ( a * e - b * d ), sq_nonneg ( a * f - c * d ), sq_nonneg ( a * h - g * d ), sq_nonneg ( b * f - c * e ), sq_nonneg ( b * h - g * e ), sq_nonneg ( c * h - g * f ) ] ;
      convert h_cauchy_schwarz ( Real.sqrt ( d * ( d + 1 ) * ( w1 ^ ( d - 1 ) * x1 * y1 ) ) ) ( Real.sqrt ( ( d + 1 ) * ( w1 ^ d * x1 ) ) ) ( Real.sqrt ( ( d + 1 ) * ( w1 ^ d * y1 ) ) ) ( Real.sqrt ( d * ( d + 1 ) * ( w2 ^ ( d - 1 ) * x2 * y2 ) ) ) ( Real.sqrt ( ( d + 1 ) * ( w2 ^ d * x2 ) ) ) ( Real.sqrt ( ( d + 1 ) * ( w2 ^ d * y2 ) ) ) ( Real.sqrt ( w1 ^ ( d + 1 ) ) ) ( Real.sqrt ( w2 ^ ( d + 1 ) ) ) ( by positivity ) ( by positivity ) ( by positivity ) ( by positivity ) ( by positivity ) ( by positivity ) ( by positivity ) ( by positivity ) using 1 <;> norm_num [ hw1, hx1, hy1, hw2, hx2, hy2 ];
      · repeat first | rw [ Real.sqrt_mul <| by positivity ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | rw [ Real.sqrt_mul <| by unreachable! ] | ring;
        rcases d with ( _ | d ) <;> norm_num [ pow_succ, pow_mul', mul_assoc, hw1, hx1, hy1, hw2, hx2, hy2 ] ; ring_nf at * ; ring;
        rw [ show ( Real.sqrt ( 2 + d ) ) ^ 4 = ( Real.sqrt ( 2 + d ) ^ 2 ) ^ 2 by ring, show ( Real.sqrt ( 1 + d ) ) ^ 4 = ( Real.sqrt ( 1 + d ) ^ 2 ) ^ 2 by ring, Real.sq_sqrt <| by positivity, Real.sq_sqrt <| by positivity ] ; norm_num [ pow_mul', hw1, hx1, hy1, hw2, hx2, hy2 ] ; ring;
        rw [ show ( Real.sqrt ( 2 + d ) ) ^ 4 = ( Real.sqrt ( 2 + d ) ^ 2 ) ^ 2 by ring, show ( Real.sqrt ( 1 + d ) ) ^ 4 = ( Real.sqrt ( 1 + d ) ^ 2 ) ^ 2 by ring, Real.sq_sqrt <| by positivity, Real.sq_sqrt <| by positivity ] ; norm_num [ pow_three, hw1, hx1, hy1, hw2, hx2, hy2 ] ; ring;
      · repeat first | rw [ Real.sq_sqrt ( by positivity ) ] | ring;

/-
Forward direction of S_d characterization for w > 0.
-/
lemma Sd_implies_h_homog_pos_w (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d)
    (w x y : ℝ) (hw : w > 0) (hx : x ≥ 0) (hy : y ≥ 0) :
    a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
      -- Apply the definition of $S_d$ to obtain the inequality.
      have h_ineq : a.1 + a.2.1 * (x / w) + a.2.2 * (y / w) ≥ A_d (d + 1) (x / w) (y / w) ^ (1 / (d + 1 : ℝ)) := by
        exact ha.2.2.2 _ _ ( div_nonneg hx hw.le ) ( div_nonneg hy hw.le );
      -- Substitute the expression for $h_homog$ into the inequality.
      have h_subst : (h_homog d w x y) = w ^ (d + 1) * A_d (d + 1) (x / w) (y / w) := by
        exact h_homog_eq_Ad d w x y hw;
      by_cases h : A_d ( d + 1 ) ( x / w ) ( y / w ) ≥ 0 <;> simp_all +decide [ mul_assoc, mul_div_cancel₀ _ hw.ne' ];
      · rw [ Real.mul_rpow ( by positivity ) ( by positivity ), ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ), Nat.cast_add_one, mul_inv_cancel₀ ( by positivity ), Real.rpow_one ];
        convert mul_le_mul_of_nonneg_left h_ineq hw.le using 1 ; ring;
        simp +decide [ mul_assoc, mul_comm w, hw.ne' ];
      · exact False.elim <| h.not_le <| by exact add_nonneg ( add_nonneg ( mul_nonneg ( mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) <| sub_nonneg.mpr <| Nat.one_le_cast.mpr <| by linarith ) <| div_nonneg hx hw.le ) <| div_nonneg hy hw.le ) <| mul_nonneg ( Nat.cast_nonneg _ ) <| add_nonneg ( div_nonneg hx hw.le ) <| div_nonneg hy hw.le ) zero_le_one;

/-
Forward direction of S_d characterization for w > 0.
-/
lemma Sd_implies_h_homog_pos_w' (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d)
    (w x y : ℝ) (hw : w > 0) (hx : x ≥ 0) (hy : y ≥ 0) :
    a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
      exact?

/-
Forward direction of S_d characterization for w > 0.
-/
lemma Sd_implies_h_homog_pos_w_new (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d)
    (w x y : ℝ) (hw : w > 0) (hx : x ≥ 0) (hy : y ≥ 0) :
    a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
      have := Sd_implies_h_homog_pos_w' d hd a ha w x y hw hx hy; aesop;

/-
Forward direction of S_d characterization (full).
-/
lemma Sd_implies_h_homog_new (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d) :
    ∀ w x y, w ≥ 0 → x ≥ 0 → y ≥ 0 →
    a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
      intro w x y hw hx hy;
      by_cases hw0 : w = 0;
      · -- By continuity of $h_homog$, we can take the limit as $w \to 0$.
        have h_cont : Filter.Tendsto (fun w => a.1 * w + a.2.1 * x + a.2.2 * y - h_homog d w x y ^ (1 / (d + 1 : ℝ))) (nhdsWithin 0 (Set.Ioi 0)) (nhds (a.2.1 * x + a.2.2 * y - (h_homog d 0 x y) ^ (1 / (d + 1 : ℝ)))) := by
          refine' Filter.Tendsto.sub _ _;
          · exact tendsto_nhdsWithin_of_tendsto_nhds ( Continuous.tendsto' ( by continuity ) _ _ ( by norm_num ) );
          · refine' Filter.Tendsto.rpow _ _ _;
            · exact Continuous.continuousWithinAt ( by unfold h_homog; continuity );
            · exact tendsto_const_nhds;
            · exact Or.inr ( by positivity );
        have h_cont : ∀ᶠ w in nhdsWithin 0 (Set.Ioi 0), a.1 * w + a.2.1 * x + a.2.2 * y - (h_homog d w x y) ^ (1 / (d + 1 : ℝ)) ≥ 0 := by
          filter_upwards [ self_mem_nhdsWithin ] with w hw;
          have := Sd_implies_h_homog_pos_w_new d hd a ha w x y hw hx hy;
          linarith;
        have := le_of_tendsto_of_tendsto tendsto_const_nhds ‹_› h_cont; aesop;
      · convert Sd_implies_h_homog_pos_w_new d hd a ha w x y ( lt_of_le_of_ne hw ( Ne.symm hw0 ) ) hx hy using 1

/-
Forward direction of S_d characterization for w = 0.
-/
lemma Sd_implies_h_homog_zero_w (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d)
    (x y : ℝ) (hx : x ≥ 0) (hy : y ≥ 0) :
    a.2.1 * x + a.2.2 * y ≥ (h_homog d 0 x y) ^ (1 / ((d : ℝ) + 1)) := by
      -- By continuity of $h_homog$ and the power function, we can take the limit as $w_n \to 0$.
      have h_lim : Filter.Tendsto (fun n : ℕ => a.1 * (1 / (n + 1)) + a.2.1 * x + a.2.2 * y) Filter.atTop (nhds (a.2.1 * x + a.2.2 * y)) := by
        exact le_trans ( Filter.Tendsto.add ( Filter.Tendsto.add ( tendsto_const_nhds.mul ( tendsto_one_div_add_atTop_nhds_zero_nat ) ) tendsto_const_nhds ) tendsto_const_nhds ) ( by norm_num );
      -- By continuity of $h_homog$ and the power function, we can take the limit as $w_n \to 0$ in the inequality.
      have h_lim_ineq : Filter.Tendsto (fun n : ℕ => (h_homog d (1 / (n + 1)) x y) ^ (1 / (d + 1 : ℝ))) Filter.atTop (nhds ((h_homog d 0 x y) ^ (1 / (d + 1 : ℝ)))) := by
        refine' Filter.Tendsto.rpow _ _ _;
        · refine' Filter.Tendsto.add ( Filter.Tendsto.add _ _ ) _;
          · by_cases h : d - 1 = 0 <;> simp_all +decide [ Nat.succ_div ];
            exact le_trans ( Filter.Tendsto.mul ( Filter.Tendsto.mul ( tendsto_const_nhds.mul ( tendsto_inv_atTop_zero.comp ( Filter.tendsto_pow_atTop ( by positivity ) |> Filter.Tendsto.comp <| Filter.tendsto_atTop_add_const_right _ _ tendsto_natCast_atTop_atTop ) ) ) tendsto_const_nhds ) tendsto_const_nhds ) ( by norm_num );
          · exact Filter.Tendsto.mul ( tendsto_const_nhds.mul ( Filter.Tendsto.pow ( tendsto_one_div_add_atTop_nhds_zero_nat ) _ ) ) tendsto_const_nhds;
          · exact Filter.Tendsto.pow ( tendsto_one_div_add_atTop_nhds_zero_nat ) _;
        · exact tendsto_const_nhds;
        · exact Or.inr ( by positivity );
      exact le_of_tendsto_of_tendsto' h_lim_ineq h_lim fun n => by simpa using Sd_implies_h_homog_pos_w_new d hd a ha ( 1 / ( n + 1 ) ) x y ( by positivity ) hx hy;

/-
Forward direction of S_d characterization (full).
-/
lemma Sd_implies_h_homog_combined (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ) (ha : a ∈ S_d d) :
    ∀ w x y, w ≥ 0 → x ≥ 0 → y ≥ 0 →
    a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
      convert Sd_implies_h_homog_new d hd a ha using 1

/-
Log-convexity of S_d.
-/
lemma Sk_convex (d : ℕ) (hd : d ≥ 2) (a b : ℝ × ℝ × ℝ) (ha : a ∈ S_d d) (hb : b ∈ S_d d) :
    (Real.sqrt (a.1 * b.1), Real.sqrt (a.2.1 * b.2.1), Real.sqrt (a.2.2 * b.2.2)) ∈ S_d d := by
      constructor;
      · exact Real.sqrt_pos.mpr ( mul_pos ha.1 hb.1 );
      · have h_combined : ∀ w x y : ℝ, w ≥ 0 → x ≥ 0 → y ≥ 0 →
            Real.sqrt (a.1 * b.1) * w + Real.sqrt (a.2.1 * b.2.1) * x + Real.sqrt (a.2.2 * b.2.2) * y ≥
            (h_homog d w x y) ^ (1 / ((d : ℝ) + 1)) := by
              field_simp;
              intro w x y hw hx hy;
              -- By the properties of the homogenized function and the Cauchy-Schwarz inequality, we have:
              have h_cauchy_schwarz : (h_homog d w x y) ^ (2 / ((d : ℝ) + 1)) ≤
                  (a.1 * (Real.sqrt (b.1 / a.1) * w) + a.2.1 * (Real.sqrt (b.2.1 / a.2.1) * x) + a.2.2 * (Real.sqrt (b.2.2 / a.2.2) * y)) *
                  (b.1 * (Real.sqrt (a.1 / b.1) * w) + b.2.1 * (Real.sqrt (a.2.1 / b.2.1) * x) + b.2.2 * (Real.sqrt (a.2.2 / b.2.2) * y)) := by
                    have h_cauchy_schwarz : (h_homog d w x y) ^ 2 ≤
                        (h_homog d (Real.sqrt (b.1 / a.1) * w) (Real.sqrt (b.2.1 / a.2.1) * x) (Real.sqrt (b.2.2 / a.2.2) * y)) *
                        (h_homog d (Real.sqrt (a.1 / b.1) * w) (Real.sqrt (a.2.1 / b.2.1) * x) (Real.sqrt (a.2.2 / b.2.2) * y)) := by
                          convert h_homog_cauchy_schwarz d ( Real.sqrt ( b.1 / a.1 ) * w ) ( Real.sqrt ( b.2.1 / a.2.1 ) * x ) ( Real.sqrt ( b.2.2 / a.2.2 ) * y ) ( Real.sqrt ( a.1 / b.1 ) * w ) ( Real.sqrt ( a.2.1 / b.2.1 ) * x ) ( Real.sqrt ( a.2.2 / b.2.2 ) * y ) ?_ ?_ ?_ ?_ ?_ ?_ using 1 <;> ring;
                          any_goals positivity;
                          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hw, hx, hy, ha.1, ha.2.1, ha.2.2.1, hb.1, hb.2.1, hb.2.2.1 ];
                          simp +decide [ mul_assoc, mul_comm, mul_left_comm, Real.sqrt_mul_self, ha.1.le, ha.2.1.le, ha.2.2.1.le, hb.1.le, hb.2.1.le, hb.2.2.1.le ];
                          simp +decide [ ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr ha.1 ) ), ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr hb.1 ) ), ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr ha.2.1 ) ), ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr hb.2.1 ) ), ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr ha.2.2.1 ) ), ne_of_gt ( Real.sqrt_pos.mpr ( Real.sqrt_pos.mpr hb.2.2.1 ) ) ];
                    have h_cauchy_schwarz : (h_homog d w x y) ^ (2 / ((d : ℝ) + 1)) ≤
                        ((h_homog d (Real.sqrt (b.1 / a.1) * w) (Real.sqrt (b.2.1 / a.2.1) * x) (Real.sqrt (b.2.2 / a.2.2) * y)) ^
                        (1 / ((d : ℝ) + 1))) *
                        ((h_homog d (Real.sqrt (a.1 / b.1) * w) (Real.sqrt (a.2.1 / b.2.1) * x) (Real.sqrt (a.2.2 / b.2.2) * y)) ^
                        (1 / ((d : ℝ) + 1))) := by
                          convert Real.rpow_le_rpow ( ?_ ) h_cauchy_schwarz ( show ( 0 : ℝ ) ≤ 1 / ( d + 1 ) by positivity ) using 1;
                          · rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by exact add_nonneg ( add_nonneg ( mul_nonneg ( mul_nonneg ( mul_nonneg ( by positivity ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) ] ; ring;
                          · rw [ Real.mul_rpow ( _ ) ( _ ) ];
                            · exact add_nonneg ( add_nonneg ( mul_nonneg ( mul_nonneg ( mul_nonneg ( by positivity ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) ( mul_nonneg ( mul_nonneg ( by positivity ) ( by positivity ) ) ( by positivity ) ) ) ( by positivity );
                            · exact add_nonneg ( add_nonneg ( mul_nonneg ( mul_nonneg ( mul_nonneg ( by positivity ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) ( mul_nonneg ( by positivity ) ( by positivity ) ) ) ( by positivity );
                          · positivity;
                    refine le_trans h_cauchy_schwarz ?_;
                    gcongr;
                    · apply_rules [ Real.rpow_nonneg, add_nonneg, mul_nonneg, pow_nonneg ];
                      all_goals norm_num [ Real.sqrt_nonneg ];
                    · exact add_nonneg ( add_nonneg ( mul_nonneg ( by linarith [ ha.1 ] ) ( mul_nonneg ( Real.sqrt_nonneg _ ) hw ) ) ( mul_nonneg ( by linarith [ ha.2.1 ] ) ( mul_nonneg ( Real.sqrt_nonneg _ ) hx ) ) ) ( mul_nonneg ( by linarith [ ha.2.2.1 ] ) ( mul_nonneg ( Real.sqrt_nonneg _ ) hy ) );
                    · exact Sd_implies_h_homog_combined d ( by linarith ) a ha _ _ _ ( by positivity ) ( by positivity ) ( by positivity );
                    · convert Sd_implies_h_homog_combined d ( by linarith ) b hb _ _ _ _ _ _ using 1 <;> ring <;> norm_num [ hw, hx, hy ];
                      · positivity;
                      · positivity;
                      · positivity;
              have h_combined : (a.1 * (Real.sqrt (b.1 / a.1) * w) + a.2.1 * (Real.sqrt (b.2.1 / a.2.1) * x) + a.2.2 * (Real.sqrt (b.2.2 / a.2.2) * y)) *
                                  (b.1 * (Real.sqrt (a.1 / b.1) * w) + b.2.1 * (Real.sqrt (a.2.1 / b.2.1) * x) + b.2.2 * (Real.sqrt (a.2.2 / b.2.2) * y)) ≤
                                  (w * Real.sqrt (a.1 * b.1) + x * Real.sqrt (a.2.1 * b.2.1) + y * Real.sqrt (a.2.2 * b.2.2)) ^ 2 := by
                                    -- By simplifying each term, we can see that the product of the two expressions is equal to the square of the sum.
                                    have h_simplify : a.1 * (Real.sqrt (b.1 / a.1) * w) = w * Real.sqrt (a.1 * b.1) ∧ a.2.1 * (Real.sqrt (b.2.1 / a.2.1) * x) = x * Real.sqrt (a.2.1 * b.2.1) ∧ a.2.2 * (Real.sqrt (b.2.2 / a.2.2) * y) = y * Real.sqrt (a.2.2 * b.2.2) ∧
                                                       b.1 * (Real.sqrt (a.1 / b.1) * w) = w * Real.sqrt (a.1 * b.1) ∧ b.2.1 * (Real.sqrt (a.2.1 / b.2.1) * x) = x * Real.sqrt (a.2.1 * b.2.1) ∧ b.2.2 * (Real.sqrt (a.2.2 / b.2.2) * y) = y * Real.sqrt (a.2.2 * b.2.2) := by
                                                         have h_simplify : ∀ {p q : ℝ}, 0 < p → 0 < q → p * Real.sqrt (q / p) = Real.sqrt (p * q) := by
                                                           intro p q hp hq; rw [ show p * q = p ^ 2 * ( q / p ) by nlinarith [ mul_div_cancel₀ q hp.ne' ], Real.sqrt_mul ( sq_nonneg _ ), Real.sqrt_sq hp.le ] ;
                                                         have h_simplify : 0 < a.1 ∧ 0 < a.2.1 ∧ 0 < a.2.2 ∧ 0 < b.1 ∧ 0 < b.2.1 ∧ 0 < b.2.2 := by
                                                           exact ⟨ ha.1, ha.2.1, ha.2.2.1, hb.1, hb.2.1, hb.2.2.1 ⟩;
                                                         simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ];
                                    rw [ h_simplify.1, h_simplify.2.1, h_simplify.2.2.1, h_simplify.2.2.2.1, h_simplify.2.2.2.2.1, h_simplify.2.2.2.2.2 ] ; ring_nf ; norm_num;
              contrapose! h_cauchy_schwarz;
              exact lt_of_le_of_lt h_combined ( by convert pow_lt_pow_left₀ h_cauchy_schwarz ( by exact add_nonneg ( add_nonneg ( mul_nonneg hw ( Real.sqrt_nonneg _ ) ) ( mul_nonneg hx ( Real.sqrt_nonneg _ ) ) ) ( mul_nonneg hy ( Real.sqrt_nonneg _ ) ) ) two_ne_zero using 1 ; rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by exact ( show 0 ≤ h_homog d w x y from by { unfold h_homog; positivity } ) ) ] ; ring );
        refine' ⟨ Real.sqrt_pos.mpr ( mul_pos ( ha.2.1 ) ( hb.2.1 ) ), Real.sqrt_pos.mpr ( mul_pos ( ha.2.2.1 ) ( hb.2.2.1 ) ), fun x y hx hy => _ ⟩;
        convert h_combined 1 x y zero_le_one hx hy using 1 ; norm_num [ h_homog ];
        unfold A_d h_homog; ring;
        push_cast; ring

/-
Reverse direction of S_d characterization.
-/
lemma h_homog_implies_Sd (d : ℕ) (hd : d ≥ 1) (a : ℝ × ℝ × ℝ)
    (h_pos : a.1 > 0 ∧ a.2.1 > 0 ∧ a.2.2 > 0)
    (h_ineq : ∀ w x y, w ≥ 0 → x ≥ 0 → y ≥ 0 →
      a.1 * w + a.2.1 * x + a.2.2 * y ≥ (h_homog d w x y) ^ (1 / ((d : ℝ) + 1))) :
    a ∈ S_d d := by
      refine' ⟨ h_pos.1, h_pos.2.1, h_pos.2.2, _ ⟩;
      exact fun x y hx hy => by simpa [ h_homog_eq_Ad _ _ _ _ zero_lt_one ] using h_ineq 1 x y zero_le_one hx hy;

/-
Log-convexity of S_d.
-/
lemma Sk_convex_new (d : ℕ) (hd : d ≥ 2) (a b : ℝ × ℝ × ℝ) (ha : a ∈ S_d d) (hb : b ∈ S_d d) :
    (Real.sqrt (a.1 * b.1), Real.sqrt (a.2.1 * b.2.1), Real.sqrt (a.2.2 * b.2.2)) ∈ S_d d := by
      convert Sk_convex d hd a b ha hb using 1

/-
Derivative of H_func.
-/
noncomputable def H_func (d : ℕ) (x : ℝ) : ℝ := A_d d x x / B_d d x

lemma H_func_deriv (d : ℕ) (hd : d ≥ 1) (x : ℝ) (hx : x ≥ 0) :
    HasDerivAt (H_func d) ((d - 1 : ℝ) + 1 / ((d : ℝ) * x + 1) ^ 2) x := by
      convert HasDerivAt.div ( HasDerivAt.add ( HasDerivAt.const_mul ( ( d : ℝ ) * ( d - 1 ) ) ( hasDerivAt_pow 2 x ) ) ( HasDerivAt.const_mul ( ( d : ℝ ) * 2 ) ( hasDerivAt_id x ) ) |> HasDerivAt.add <| hasDerivAt_const _ _ ) ( HasDerivAt.add ( HasDerivAt.const_mul ( ( d : ℝ ) ) ( hasDerivAt_id x ) ) <| hasDerivAt_const _ _ ) _ using 1 <;> norm_num;
      rotate_left;
      rotate_left;
      exact 1;
      exact 1;
      · positivity;
      · ext; norm_num; ring;
        unfold H_func; ring;
        unfold A_d B_d; ring;
      · rw [ inv_eq_one_div, add_div' ] <;> ring ; positivity

/-
Strict monotonicity of H_func.
-/
lemma H_func_strict_mono (d : ℕ) (hd : d ≥ 1) : StrictMonoOn (H_func d) (Set.Ici 0) := by
  -- The derivative of $H_d(x)$ is $(d-1) + \frac{1}{(dx+1)^2}$.
  have h_H_deriv : ∀ x : ℝ, x ≥ 0 → HasDerivAt (H_func d) ((d - 1 : ℝ) + 1 / ((d : ℝ) * x + 1) ^ 2) x := by
    exact?;
  apply_rules [ strictMonoOn_of_deriv_pos, h_H_deriv ];
  · exact convex_Ici 0;
  · exact continuousOn_of_forall_continuousAt fun x hx => HasDerivAt.continuousAt ( h_H_deriv x hx );
  · norm_num +zetaDelta at *;
    exact fun x hx => HasDerivAt.deriv ( h_H_deriv x hx.le ) ▸ by exact add_pos_of_nonneg_of_pos ( sub_nonneg.mpr ( Nat.one_le_cast.mpr hd ) ) ( inv_pos.mpr ( sq_pos_of_pos ( by positivity ) ) ) ;

/-
H_func is at least 1.
-/
lemma H_func_ge_one (d : ℕ) (hd : d ≥ 1) (x : ℝ) (hx : x ≥ 0) : H_func d x ≥ 1 := by
  exact le_trans ( by norm_num [ H_func, A_d, B_d ] ) ( H_func_strict_mono d hd |> fun h => h.le_iff_le ( by norm_num ) ( by norm_num ; positivity ) |>.2 hx )

/-
Inequality for H_func.
-/
lemma H_func_ineq (d : ℕ) (hd : d ≥ 1) (x s : ℝ) (hx : x ≥ 0) (hs : s ≥ 1)
    (h_eq : H_func d x = s ^ d) :
    H_func (d + 1) (s * x) ≥ s ^ (d + 1) := by
      -- Let $Q(x)$ be the numerator of the combined fraction over $((d+1)s+d)x+1$.
      set Q : ℝ → ℝ := fun x => 2 * s * d * x^2 + (2 * s + d - s^2 * d - s^2) * x - (s - 1);
      -- We need to show that $Q(x) \ge 0$ for $x \ge s-1$.
      have hQ_nonneg : ∀ x, x ≥ s - 1 → Q x ≥ 0 := by
        -- We need to show that $Q(s-1) \ge 0$.
        have hQ_s_minus_1 : Q (s - 1) ≥ 0 := by
          nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, mul_le_mul_of_nonneg_left hs <| show 0 ≤ ( d : ℝ ) * ( s - 1 ) by exact mul_nonneg ( Nat.cast_nonneg _ ) <| sub_nonneg.mpr hs, mul_le_mul_of_nonneg_left hs <| show 0 ≤ ( d : ℝ ) * ( s - 1 ) ^ 2 by exact mul_nonneg ( Nat.cast_nonneg _ ) <| sq_nonneg _ ];
        -- Since $Q(x)$ is a quadratic function with a positive leading coefficient, it is increasing for $x \ge s-1$.
        have hQ_incr : ∀ x ≥ s - 1, deriv Q x ≥ 0 := by
          norm_num [ Q, mul_comm ];
          intro x hx; nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, show ( s : ℝ ) ≥ 1 by norm_cast, mul_le_mul_of_nonneg_left hs ( show ( d : ℝ ) ≥ 0 by positivity ), mul_le_mul_of_nonneg_left hx ( show ( d : ℝ ) ≥ 0 by positivity ), sq_nonneg ( s - 1 ) ] ;
        intro x hx; by_contra h_neg; push_neg at h_neg; (
        -- Apply the Mean Value Theorem to Q on the interval [s-1, x].
        obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo (s - 1) x, deriv Q c = (Q x - Q (s - 1)) / (x - (s - 1)) := by
          apply_rules [ exists_deriv_eq_slope ];
          · exact hx.lt_of_ne ( by rintro rfl; linarith );
          · fun_prop;
          · fun_prop;
        rw [ eq_div_iff ] at hc <;> nlinarith [ hc.1.1, hc.1.2, hQ_incr c hc.1.1.le ]);
      -- By definition of $H_func$, we know that $H_func (d + 1) (s * x) \geq s^{d + 1}$ if and only if $Q(x) \geq 0$.
      have hH_ge_s_pow : H_func (d + 1) (s * x) - s ^ (d + 1) ≥ (Q x) / (((d + 1) * s + d) * x + 1) := by
        -- Substitute the expression for $H_func (d + 1) (s * x) - s^{d + 1}$ from the provided solution.
        have h_subst : H_func (d + 1) (s * x) - s ^ (d + 1) = (1 - s) + s * x + s * x * ((d - (d + 1) * s) * x) / (((d + 1) * s * x + 1) * (d * x + 1)) := by
          unfold H_func;
          unfold A_d B_d; ring;
          field_simp;
          unfold H_func at h_eq; rw [ div_eq_iff ] at h_eq <;> norm_num [ A_d, B_d ] at * <;> try nlinarith;
          grind;
        -- Since $((d+1)sx+1)(dx+1) \ge ((d+1)s+d)x + 1$, we have $s * x * ((d - (d + 1) * s) * x) / (((d + 1) * s * x + 1) * (d * x + 1)) \ge s * x * ((d - (d + 1) * s) * x) / (((d + 1) * s + d) * x + 1)$.
        have h_frac_ge : s * x * ((d - (d + 1) * s) * x) / (((d + 1) * s * x + 1) * (d * x + 1)) ≥ s * x * ((d - (d + 1) * s) * x) / (((d + 1) * s + d) * x + 1) := by
          by_cases h_case : (d - (d + 1) * s) * x ≤ 0;
          · rw [ ge_iff_le, div_le_div_iff₀ ] <;> try positivity;
            exact mul_le_mul_of_nonpos_left ( by nlinarith [ show ( d : ℝ ) * x ≥ 0 by positivity, show ( d : ℝ ) * s * x ≥ 0 by positivity, show ( d : ℝ ) * s ≥ 0 by positivity, show ( d : ℝ ) ≥ 1 by norm_cast, show ( s : ℝ ) ≥ 1 by norm_cast, sq_nonneg ( x * ( d : ℝ ) ), sq_nonneg ( x * ( d + 1 : ℝ ) ), sq_nonneg ( s * ( d : ℝ ) ), sq_nonneg ( s * ( d + 1 : ℝ ) ) ] ) ( by nlinarith [ show ( d : ℝ ) * x ≥ 0 by positivity, show ( d : ℝ ) * s * x ≥ 0 by positivity, show ( d : ℝ ) * s ≥ 0 by positivity, show ( d : ℝ ) ≥ 1 by norm_cast, show ( s : ℝ ) ≥ 1 by norm_cast, sq_nonneg ( x * ( d : ℝ ) ), sq_nonneg ( x * ( d + 1 : ℝ ) ), sq_nonneg ( s * ( d : ℝ ) ), sq_nonneg ( s * ( d + 1 : ℝ ) ) ] );
          · exact False.elim <| h_case <| mul_nonpos_of_nonpos_of_nonneg ( sub_nonpos_of_le <| by nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast ] ) hx;
        simp +zetaDelta at *;
        convert add_le_add_left h_frac_ge ( 1 - s + s * x ) using 1 ; ring;
        nlinarith [ inv_mul_cancel_left₀ ( by positivity : ( 1 + s * d * x + s * x + d * x ) ≠ 0 ) s, inv_mul_cancel_left₀ ( by positivity : ( 1 + s * d * x + s * x + d * x ) ≠ 0 ) x, inv_mul_cancel₀ ( by positivity : ( 1 + s * d * x + s * x + d * x ) ≠ 0 ) ];
      -- Since $x \geq s - 1$, we can apply $hQ_nonneg$ to conclude that $Q(x) \geq 0$.
      have hx_ge_s_minus_1 : x ≥ s - 1 := by
        -- By Bernoulli's inequality, we have $(1 + (s-1))^d \geq 1 + d(s-1)$.
        have h_bernoulli : (1 + (s - 1)) ^ d ≥ 1 + d * (s - 1) := by
          exact one_add_mul_le_pow ( by linarith ) _ |> le_trans ( by norm_num );
        -- By definition of $H_func$, we know that $H_func d x = s^d$ implies $s^d \leq 1 + d*x$.
        have h_s_d_le : s ^ d ≤ 1 + d * x := by
          unfold H_func at h_eq;
          unfold A_d B_d at h_eq;
          rw [ ← h_eq, div_le_iff₀ ] <;> nlinarith [ show ( d : ℝ ) ≥ 1 by norm_cast, mul_nonneg ( Nat.cast_nonneg d ) hx ];
        norm_num at * ; nlinarith [ ( by norm_cast : ( 1 :ℝ ) ≤ d ) ];
      exact le_of_sub_nonneg ( hH_ge_s_pow.trans' ( div_nonneg ( hQ_nonneg x hx_ge_s_minus_1 ) ( by positivity ) ) )

/-
Definition of x_func using epsilon.
-/
noncomputable def x_func (d : ℕ) (s : ℝ) : ℝ :=
  Classical.epsilon (fun x => x ≥ 0 ∧ H_func d x = s ^ d)

/-
Limit of H_func at infinity.
-/
lemma H_func_tendsto_atTop (d : ℕ) (hd : d ≥ 2) :
    Filter.Tendsto (H_func d) Filter.atTop Filter.atTop := by
      -- We can simplify the expression for H_func d x as x approaches infinity.
      have h_simplify : Filter.Tendsto (fun x : ℝ => (d * (d - 1) * x ^ 2 + 2 * d * x + 1) / (d * x + 1)) Filter.atTop Filter.atTop := by
        refine' Filter.tendsto_atTop_atTop.mpr fun x => _;
        exact ⟨ Max.max x 1, fun a ha => by rw [ le_div_iff₀ ] <;> nlinarith [ le_max_left x 1, le_max_right x 1, show ( d : ℝ ) ≥ 2 by norm_cast, mul_le_mul_of_nonneg_left ( show ( d : ℝ ) ≥ 2 by norm_cast ) ( by linarith [ le_max_left x 1, le_max_right x 1 ] : ( 0 : ℝ ) ≤ a ) ] ⟩;
      convert h_simplify using 2 ; unfold H_func ; unfold A_d B_d ; ring

/-
Value of H_func at 0.
-/
lemma H_func_zero (d : ℕ) : H_func d 0 = 1 := by
  unfold H_func A_d B_d; norm_num;

/-
Property of x_func for d >= 2.
-/
lemma x_func_spec (d : ℕ) (hd : d ≥ 2) (s : ℝ) (hs : s ≥ 1) :
    x_func d s ≥ 0 ∧ H_func d (x_func d s) = s ^ d := by
      -- By the properties of the intermediate value theorem, since $H_func d$ is continuous on $[0, \infty)$ and $H_func d(0) = 1$, there exists $x \geq 0$ such that $H_func d(x) = s^d$.
      have h_ivt : ∃ x ∈ Set.Ici 0, H_func d x = s ^ d := by
        have h_cont : ContinuousOn (H_func d) (Set.Ici 0) := by
          refine' ContinuousOn.div _ _ _;
          · exact Continuous.continuousOn ( by unfold A_d; continuity );
          · exact Continuous.continuousOn ( by unfold B_d; continuity );
          · exact fun x hx => ne_of_gt <| add_pos_of_nonneg_of_pos ( mul_nonneg ( Nat.cast_nonneg _ ) hx ) zero_lt_one
        have h_lim : Filter.Tendsto (H_func d) Filter.atTop Filter.atTop := by
          convert H_func_tendsto_atTop d hd using 1
        have h_ivt : ∃ x ∈ Set.Ici 0, H_func d x ≥ s ^ d := by
          exact Filter.Eventually.and ( Filter.eventually_ge_atTop 0 ) ( h_lim.eventually_ge_atTop _ ) |> fun h => h.exists;
        have h_ivt : ∃ x ∈ Set.Icc 0 (h_ivt.choose), H_func d x = s ^ d := by
          apply_rules [ intermediate_value_Icc ];
          · exact h_ivt.choose_spec.1;
          · exact h_cont.mono <| Set.Icc_subset_Ici_self;
          · exact ⟨ by rw [ H_func_zero ] ; exact one_le_pow₀ hs, h_ivt.choose_spec.2 ⟩;
        exact ⟨ h_ivt.choose, h_ivt.choose_spec.1.1, h_ivt.choose_spec.2 ⟩;
      exact Classical.epsilon_spec h_ivt |> fun h => ⟨ h.1, h.2 ⟩

/-
Definition of Phi_func.
-/
noncomputable def Phi_func (d : ℕ) (s : ℝ) : ℝ :=
  (B_d d (x_func d s)) ^ (1 / (d : ℝ)) / (A_d (d + 1) (x_func d s) (x_func d s)) ^ (1 / ((d : ℝ) + 1))
