/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 738dfd52-761b-489e-8cad-7b1ff490c1e1

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The set of all independent sets of a graph G.
-/
open SimpleGraph Finset BigOperators

variable {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj]

def SimpleGraph.indepSets : Finset (Finset V) :=
  univ.filter (fun s => G.IsIndepSet s)

/-
The partition function Z_G^{(2)}(λ, μ) defined as the sum over pairs of disjoint independent sets (I, J) of (prod_{v in I} λ_v) * (prod_{u in J} μ_u).
-/
noncomputable def SimpleGraph.ZG2 {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj]
    (lambda : V → ℝ) (mu : V → ℝ) : ℝ :=
  ∑ I ∈ G.indepSets, ∑ J ∈ G.indepSets, if Disjoint I J then (∏ v ∈ I, lambda v) * (∏ u ∈ J, mu u) else 0

/-
The term appearing in the lower bound of Theorem 1.4: (d+1)dλμ + (d+1)(λ+μ) + 1.
-/
noncomputable def SimpleGraph.ZG2_lower_bound_term (d : ℕ) (lambda mu : ℝ) : ℝ :=
  (d + 1) * d * lambda * mu + (d + 1) * (lambda + mu) + 1

/-
Definitions of A_d(λ, μ) and B_d(λ) as used in Equation 553 and 556.
-/
noncomputable def A_d (d : ℕ) (lambda mu : ℝ) : ℝ :=
  (d : ℝ) * ((d : ℝ) - 1) * lambda * mu + (d : ℝ) * (lambda + mu) + 1

noncomputable def B_d (d : ℕ) (lambda : ℝ) : ℝ :=
  (d : ℝ) * lambda + 1

/-
Lemma 3.2 for the case Δ=1 (Equation 564).
-/
theorem lemma_semiprop_multiaff_lower_bd_goal_2_Delta_1
    (lambda_w mu_w lambda_v mu_v : ℝ)
    (h_lambda_w : 0 ≤ lambda_w) (h_mu_w : 0 ≤ mu_w)
    (h_lambda_v : 0 ≤ lambda_v) (h_mu_v : 0 ≤ mu_v) :
    A_d 1 lambda_v mu_v + lambda_w * B_d 1 mu_v + mu_w * B_d 1 lambda_v
    ≥ (A_d 2 lambda_w mu_w) ^ (1 / 2 : ℝ) * (A_d 2 lambda_v mu_v) ^ (1 / 2 : ℝ) := by
  -- By definition of $A_d$ and $B_d$, we can rewrite the inequality in terms of $x_1$, $y_1$, $x_2$, and $y_2$.
  set x1 := lambda_w + 1
  set y1 := mu_w + 1
  set x2 := lambda_v + 1
  set y2 := mu_v + 1
  have h_rewrite : x1 * y2 + y1 * x2 - 1 ≥ (((2 * x1 * y1 - 1) * (2 * x2 * y2 - 1)) ^ (1 / 2 : ℝ)) := by
    -- By AM-GM, $x_1 y_2 + y_1 x_2 - 1 \geq 2 \sqrt{x_1 y_2 y_1 x_2} - 1$.
    have h_am_gm : x1 * y2 + y1 * x2 - 1 ≥ 2 * Real.sqrt (x1 * y2 * y1 * x2) - 1 := by
      nlinarith only [ sq_nonneg ( x1 * y2 - y1 * x2 ), show 0 ≤ x1 * y2 by positivity, show 0 ≤ y1 * x2 by positivity, Real.mul_self_sqrt ( show 0 ≤ x1 * y2 * y1 * x2 by positivity ) ];
    -- Let $x = \sqrt{x_1 y_1}$ and $y = \sqrt{x_2 y_2}$.
    set x := Real.sqrt (x1 * y1)
    set y := Real.sqrt (x2 * y2);
    -- Then we need to show $2xy - 1 \geq \sqrt{2x^2 - 1} \cdot \sqrt{2y^2 - 1}$.
    suffices h_xy : 2 * x * y - 1 ≥ Real.sqrt (2 * x^2 - 1) * Real.sqrt (2 * y^2 - 1) by
      norm_num +zetaDelta at *;
      rw [ ← Real.sqrt_eq_rpow ] ; convert h_xy.trans _ using 1 <;> norm_num [ mul_assoc, Real.sq_sqrt ( by positivity : 0 ≤ ( lambda_w + 1 ) * ( mu_w + 1 ) ), Real.sq_sqrt ( by positivity : 0 ≤ ( lambda_v + 1 ) * ( mu_v + 1 ) ) ] ; ring_nf;
      · rw [ ← Real.sqrt_mul <| by positivity ] ; ring_nf;
      · convert h_am_gm using 1 ; rw [ ← Real.sqrt_mul <| by positivity ] ; ring_nf;
    -- Squaring both sides (since both are non-negative), we get $(2xy - 1)^2 \geq (2x^2 - 1)(2y^2 - 1)$.
    suffices h_sq : (2 * x * y - 1) ^ 2 ≥ (2 * x ^ 2 - 1) * (2 * y ^ 2 - 1) by
      rw [ ← Real.sqrt_mul ];
      · exact Real.sqrt_le_iff.mpr ⟨ by nlinarith only [ show 1 ≤ x by exact Real.le_sqrt_of_sq_le ( by ring_nf; nlinarith ), show 1 ≤ y by exact Real.le_sqrt_of_sq_le ( by ring_nf; nlinarith ) ], h_sq ⟩;
      · rw [ Real.sq_sqrt ] <;> nlinarith only [ h_lambda_w, h_mu_w, h_lambda_v, h_mu_v ];
    linarith [ sq_nonneg ( x - y ) ]
  simp +decide [ * ] at *;
  convert h_rewrite using 1 <;> norm_num [ ← Real.sqrt_eq_rpow ] ; ring_nf!;
  · rw [ ← Real.sqrt_mul <| by unfold A_d; norm_num; nlinarith ] ; unfold A_d ; ring_nf;
  · unfold A_d B_d; ring;

/-
Definition of the dual set S_d.
-/
def S_d (d : ℕ) : Set (ℝ × ℝ × ℝ) :=
  { v | v.1 > 0 ∧ v.2.1 > 0 ∧ v.2.2 > 0 ∧
    ∀ x y, x ≥ 0 → y ≥ 0 → v.1 + v.2.1 * x + v.2.2 * y ≥ (A_d (d + 1) x y) ^ (1 / ((d : ℝ) + 1)) }
