/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 9eb5cfff-15ee-40b9-81d6-031cf5a10876

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The set of all independent sets of a graph G.
-/
def indepSets {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] : Finset (Finset V) :=
  Finset.univ.powerset.filter (fun s => G.IsIndepSet s)

/-
The multivariate independence polynomial of a graph G with weights w.
-/
noncomputable def multivariateIndependencePolynomial {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {R : Type*} [CommSemiring R] (w : V → R) : R :=
  ∑ I ∈ indepSets G, ∏ v ∈ I, w v

/-
Key technical inequality (Lemma 2.1) for the lower bound proof.
-/
lemma key_tech_ineq (n : ℕ) (hn : n ≥ 1) (d : Fin n → ℕ) (hd : ∀ i, 1 ≤ d i ∧ d i ≤ n)
    (w : Fin n → ℝ) (hw : ∀ i, 0 ≤ w i) (w0 : ℝ) (hw0 : 0 ≤ w0) :
    ∏ i, (1 + (d i : ℝ) * w i) ^ (1 / (d i : ℝ)) + w0 ≥
    ((n + 1 : ℝ) * w0 + 1) ^ (1 / (n + 1 : ℝ)) * ∏ i, (1 + ((d i : ℝ) + 1) * w i) ^ (1 / ((d i : ℝ) + 1)) := by
  -- By AM-GM, $(1+(n+1)w_0)^{1/(n+1)} B \le \frac{1+(n+1)w_0 + n B^{(n+1)/n}}{n+1} = \frac{1+n B^{(n+1)/n}}{n+1} + w_0$.
  have h_am_gm : ((n + 1) * w0 + 1)^(1/(n+1 : ℝ)) * ∏ i, (1 + ((d i) + 1) * (w i))^(1/((d i) + 1) : ℝ) ≤ (1 + n * (∏ i, (1 + ((d i) + 1) * (w i))^(1/((d i) + 1) : ℝ))^( (n+1)/n : ℝ)) / (n+1) + w0 := by
    have := @Real.geom_mean_le_arith_mean;
    specialize this ( Finset.univ : Finset ( Fin ( n + 1 ) ) ) ( fun i => 1 ) ( fun i => if i = ⟨ 0, Nat.succ_pos n ⟩ then ( ( n : ℝ ) + 1 ) * w0 + 1 else ( ∏ i : Fin n, ( 1 + ( d i + 1 ) * w i ) ^ ( 1 / ( d i + 1 ) : ℝ ) ) ^ ( ( n + 1 : ℝ ) / n : ℝ ) ) ; norm_num at *;
    convert this ( by positivity ) ( fun i => by split_ifs <;> first | positivity | exact Real.rpow_nonneg ( Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ( hw _ ) ) ) _ ) _ ) using 1 <;> norm_num [ Fin.sum_univ_succ, Fin.prod_univ_succ ] ; ring;
    · rw [ ← Real.rpow_natCast _ n, ← Real.rpow_mul ( Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( add_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( Nat.cast_nonneg _ ) ( hw _ ) ) ) ( hw _ ) ) _ ) ] ; norm_num [ show n ≠ 0 by linarith ] ; ring;
      field_simp;
      rw [ Real.mul_rpow ( by exact Real.rpow_nonneg ( Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( by nlinarith [ hw ‹_› ] ) _ ) _ ) ( by positivity ), ← Real.rpow_mul ( Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( by nlinarith [ hw ‹_› ] ) _ ) ] ; ring_nf ; norm_num [ show ( 1 + n : ℝ ) ≠ 0 by positivity ] ; ring;
      exact Or.inl ( by rw [ show ( n : ℝ ) * ( 1 + n : ℝ ) ⁻¹ + ( 1 + n : ℝ ) ⁻¹ = 1 by linarith [ mul_inv_cancel₀ ( by positivity : ( 1 + n : ℝ ) ≠ 0 ) ] ] ; norm_num );
    · rw [ div_add', div_eq_div_iff ] <;> ring <;> positivity;
  -- So it suffices to show $(n+1)A \ge 1 + n B^{(n+1)/n}$.
  suffices h_suff : (n + 1) * (∏ i, (1 + (d i) * (w i))^(1/(d i : ℝ))) ≥ 1 + n * (∏ i, (1 + ((d i) + 1) * (w i))^(1/((d i) + 1) : ℝ))^( (n+1)/n : ℝ) by
    nlinarith [ mul_div_cancel₀ ( 1 + n * ( ∏ i : Fin n, ( 1 + ( d i + 1 ) * w i ) ^ ( 1 / ( d i + 1 : ℝ ) ) ) ^ ( ( n + 1 : ℝ ) / n ) ) ( by positivity : ( n : ℝ ) + 1 ≠ 0 ) ];
  -- We prove $(n+1) A_i^n \ge 1 + n B_i^{n+1}$ for each $i$.
  have h_ineq : ∀ i, (n + 1) * (1 + (d i) * (w i))^(n / (d i) : ℝ) ≥ 1 + n * (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ) := by
    intro i;
    -- Let $f(w) = (n+1)(1+d w)^{n/d} - n(1+(d+1)w)^{(n+1)/(d+1)} - 1$.
    set f : ℝ → ℝ := fun w => (n + 1) * (1 + (d i) * w)^(n / (d i) : ℝ) - n * (1 + ((d i) + 1) * w)^((n + 1) / ((d i) + 1) : ℝ) - 1;
    have hf_deriv_nonneg : ∀ w ≥ 0, deriv f w ≥ 0 := by
      intro w hw_nonneg; norm_num [ f, mul_comm ];
      norm_num [ show ( 1 + w * ( d i : ℝ ) ) ≠ 0 by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ], show ( 1 + w * ( d i + 1 : ℝ ) ) ≠ 0 by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ];
      field_simp;
      rw [ mul_div_cancel_left₀ _ ( by norm_cast; linarith [ hd i ] ) ];
      rw [ Real.rpow_def_of_pos ( by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ), Real.rpow_def_of_pos ( by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ) ];
      field_simp;
      rw [ div_sub_one, mul_div_assoc' ] <;> try norm_num ; linarith [ hd i ];
      rw [ Real.exp_le_exp ];
      rw [ div_le_div_iff₀ ( by positivity ) ( by norm_cast; linarith [ hd i ] ) ];
      -- We can divide both sides by $(n - d_i)$ since it is positive.
      have h_div : Real.log (1 + ((d i) + 1) * w) * (d i) ≤ Real.log (1 + (d i) * w) * (d i + 1) := by
        -- We can divide both sides by $(d_i + 1)$ since it is positive.
        have h_div : Real.log (1 + ((d i) + 1) * w) ≤ Real.log (1 + (d i) * w) * (1 + 1 / (d i : ℝ)) := by
          rw [ mul_add, mul_one, mul_one_div, Real.log_le_iff_le_exp ( by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ) ];
          field_simp;
          rw [ Real.exp_mul, Real.exp_log ( by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ) ];
          -- By Bernoulli's inequality, we have $(1 + x)^r \geq 1 + rx$ for $x \geq -1$ and $r \geq 1$.
          have h_bernoulli : ∀ x : ℝ, 0 ≤ x → ∀ r : ℝ, 1 ≤ r → (1 + x)^r ≥ 1 + r * x := by
            intro x hx r hr; have := @Real.geom_mean_le_arith_mean;
            specialize this { 0, 1 } ( fun i => if i = 0 then 1 else r - 1 ) ( fun i => if i = 0 then ( 1 + x ) ^ r else 1 ) ; norm_num at *;
            specialize this hr ( by linarith ) ( by positivity ) ; rw [ ← Real.rpow_mul ( by positivity ), mul_inv_cancel₀ ( by linarith ), Real.rpow_one ] at this ; rw [ le_div_iff₀ ( by linarith ) ] at this ; nlinarith;
          exact le_trans ( by nlinarith [ show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1, one_div_mul_cancel ( show ( d i : ℝ ) ≠ 0 by norm_cast; linarith [ hd i ] ) ] ) ( h_bernoulli _ ( by positivity ) _ ( by exact le_add_of_nonneg_right <| by positivity ) );
        convert mul_le_mul_of_nonneg_right h_div ( Nat.cast_nonneg ( d i ) ) using 1 ; ring;
        rw [ mul_right_comm, mul_inv_cancel₀ ( Nat.cast_ne_zero.mpr ( by linarith [ hd i ] ) ), one_mul ];
      nlinarith [ show ( d i : ℝ ) ≤ n by norm_cast; linarith [ hd i ] ];
    -- Since $f$ is differentiable and its derivative is non-negative for $w \geq 0$, we can apply the Mean Value Theorem to $f$ on the interval $[0, w_i]$.
    have h_mvt : ∀ w > 0, ∃ c ∈ Set.Ioo 0 w, deriv f c = (f w - f 0) / (w - 0) := by
      intro w hw_pos; apply_rules [ exists_deriv_eq_slope _, hw_pos ];
      · exact continuousOn_of_forall_continuousAt fun x hx => by exact ContinuousAt.sub ( ContinuousAt.sub ( ContinuousAt.mul continuousAt_const <| ContinuousAt.rpow ( continuousAt_const.add <| continuousAt_const.mul continuousAt_id ) continuousAt_const <| Or.inr <| by exact div_pos ( by positivity ) <| Nat.cast_pos.mpr <| hd i |>.1 ) <| ContinuousAt.mul continuousAt_const <| ContinuousAt.rpow ( continuousAt_const.add <| continuousAt_const.mul continuousAt_id ) continuousAt_const <| Or.inr <| by exact div_pos ( by positivity ) <| Nat.cast_add_one_pos _ ) continuousAt_const;
      · exact fun x hx => DifferentiableAt.differentiableWithinAt <| by exact DifferentiableAt.sub ( DifferentiableAt.sub ( DifferentiableAt.mul ( differentiableAt_const _ ) <| DifferentiableAt.rpow ( by norm_num [ mul_comm ] ) ( by norm_num ) <| by nlinarith [ hx.1, show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ) <| DifferentiableAt.mul ( differentiableAt_const _ ) <| DifferentiableAt.rpow ( by norm_num [ mul_comm ] ) ( by norm_num ) <| by nlinarith [ hx.1, show ( d i : ℝ ) ≥ 1 by exact_mod_cast hd i |>.1 ] ) <| differentiableAt_const _;
    simp +zetaDelta at *;
    by_cases hi : w i = 0;
    · norm_num [ hi ];
      linarith;
    · obtain ⟨ c, ⟨ hc1, hc2 ⟩, hc3 ⟩ := h_mvt ( w i ) ( lt_of_le_of_ne ( hw i ) ( Ne.symm hi ) ) ; have := hc3 ▸ hf_deriv_nonneg c hc1.le; rw [ le_div_iff₀ ( lt_of_le_of_ne ( hw i ) ( Ne.symm hi ) ) ] at this; linarith;
  -- Then $(n+1)^n A^n = \prod ((n+1) A_i^n) \ge \prod (1 + n B_i^{n+1})$.
  have h_prod_ineq : ((n + 1) : ℝ)^n * (∏ i, (1 + (d i) * (w i))^(n / (d i) : ℝ)) ≥ ∏ i, (1 + n * (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ)) := by
    exact le_trans ( Finset.prod_le_prod ( fun _ _ => by exact add_nonneg zero_le_one <| mul_nonneg ( Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( add_nonneg zero_le_one <| mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) <| hw _ ) _ ) fun _ _ => h_ineq _ ) <| by simp +decide [ Finset.prod_mul_distrib ] ;
  -- We need $\prod (1 + n B_i^{n+1}) \ge (1 + n B^{(n+1)/n})^n$.
  have h_prod_ineq2 : ∏ i, (1 + n * (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ)) ≥ (1 + n * (∏ i, (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ))^(1 / n : ℝ))^n := by
    -- Let $y_i = n B_i^{n+1}$. We need $\prod (1+y_i) \ge (1 + (\prod y_i)^{1/n})^n$.
    set y : Fin n → ℝ := fun i => n * (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ);
    -- Taking $n$-th root, $\prod (1+y_i)^{1/n} \ge 1 + (\prod y_i)^{1/n}$.
    have h_root : (∏ i, (1 + y i))^(1 / n : ℝ) ≥ 1 + (∏ i, y i)^(1 / n : ℝ) := by
      -- By the AM-GM inequality, we have $\frac{1}{n} \sum_{i=1}^n \frac{1}{1+y_i} + \frac{1}{n} \sum_{i=1}^n \frac{y_i}{1+y_i} \geq \prod_{i=1}^n \left(\frac{1}{1+y_i}\right)^{1/n} + \prod_{i=1}^n \left(\frac{y_i}{1+y_i}\right)^{1/n}$.
      have h_am_gm : (1 / n : ℝ) * ∑ i, (1 / (1 + y i)) + (1 / n : ℝ) * ∑ i, (y i / (1 + y i)) ≥ (∏ i, (1 / (1 + y i)))^(1 / n : ℝ) + (∏ i, (y i / (1 + y i)))^(1 / n : ℝ) := by
        have h_am_gm : ∀ (x : Fin n → ℝ), (∀ i, 0 ≤ x i) → (∑ i, x i) / n ≥ (∏ i, x i)^(1 / n : ℝ) := by
          have := @Real.geom_mean_le_arith_mean;
          exact fun x hx => by simpa using this Finset.univ ( fun _ => 1 ) x ( fun _ _ => zero_le_one ) ( by simpa using by positivity ) ( fun _ _ => hx _ ) ;
        exact add_le_add ( by simpa only [ one_div, inv_mul_eq_div ] using h_am_gm _ fun i => one_div_nonneg.mpr ( add_nonneg zero_le_one ( mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ( hw i ) ) ) _ ) ) ) ) ( by simpa only [ one_div, inv_mul_eq_div ] using h_am_gm _ fun i => div_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ( hw i ) ) ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ( hw i ) ) ) _ ) ) ) );
      -- Simplify the left-hand side of the inequality.
      have h_lhs_simplified : (1 / n : ℝ) * ∑ i, (1 / (1 + y i)) + (1 / n : ℝ) * ∑ i, (y i / (1 + y i)) = 1 := by
        field_simp;
        rw [ ← Finset.sum_add_distrib ] ; exact Eq.trans ( Finset.sum_congr rfl fun _ _ => by rw [ ← add_div, div_self <| by exact ne_of_gt <| add_pos_of_pos_of_nonneg zero_lt_one <| mul_nonneg ( Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( add_nonneg zero_le_one <| mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) <| hw _ ) _ ] ) <| by norm_num;
      simp +zetaDelta at *;
      rw [ Real.div_rpow ( Finset.prod_nonneg fun _ _ => mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( by nlinarith only [ hw ‹_› ] ) _ ) ) ( Finset.prod_nonneg fun _ _ => add_nonneg zero_le_one ( mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( by nlinarith only [ hw ‹_› ] ) _ ) ) ) ] at h_am_gm;
      rw [ Real.inv_rpow ( Finset.prod_nonneg fun _ _ => add_nonneg zero_le_one ( mul_nonneg ( Nat.cast_nonneg _ ) ( Real.rpow_nonneg ( by nlinarith only [ hw ‹_› ] ) _ ) ) ) ] at h_am_gm;
      rw [ inv_eq_one_div, ← add_div, div_le_iff₀ ] at h_am_gm <;> nlinarith [ show 0 < ( ∏ i : Fin n, ( 1 + ( n : ℝ ) * ( 1 + ( ( d i : ℝ ) + 1 ) * w i ) ^ ( ( n + 1 : ℝ ) / ( d i + 1 ) ) ) ) ^ ( ( n : ℝ ) ⁻¹ ) from Real.rpow_pos_of_pos ( Finset.prod_pos fun _ _ => by exact add_pos_of_pos_of_nonneg zero_lt_one <| mul_nonneg ( Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( by nlinarith only [ hw ‹_› ] ) _ ) _ ];
    -- Raising both sides to the power of $n$, we get $\prod (1 + y_i) \ge (1 + (\prod y_i)^{1/n})^n$.
    have h_exp : (∏ i, (1 + y i)) ≥ (1 + (∏ i, y i)^(1 / n : ℝ))^n := by
      exact le_trans ( pow_le_pow_left₀ ( add_nonneg zero_le_one <| Real.rpow_nonneg ( Finset.prod_nonneg fun _ _ => mul_nonneg ( Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( add_nonneg zero_le_one <| mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) <| hw _ ) _ ) _ ) h_root _ ) ( by rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( Finset.prod_nonneg fun _ _ => add_nonneg zero_le_one <| mul_nonneg ( Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( add_nonneg zero_le_one <| mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) <| hw _ ) _ ), one_div_mul_cancel <| by positivity, Real.rpow_one ] );
    convert h_exp using 2 ; norm_num [ Finset.prod_mul_distrib ];
    rw [ Finset.prod_mul_distrib, Real.mul_rpow ( by positivity ) ( Finset.prod_nonneg fun _ _ => by exact Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ( hw _ ) ) ) _ ) ] ; norm_num [ show n ≠ 0 by linarith ];
    exact Or.inl ( by rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ), mul_inv_cancel₀ ( by positivity ), Real.rpow_one ] );
  -- Combining the inequalities, we get $(n+1)^n A^n \ge (1 + n B^{(n+1)/n})^n$, which simplifies to $(n+1) A \ge 1 + n B^{(n+1)/n}$.
  have h_combined : ((n + 1) : ℝ) * (∏ i, (1 + (d i) * (w i))^(1 / (d i) : ℝ)) ≥ (1 + n * (∏ i, (1 + ((d i) + 1) * (w i))^((n + 1) / ((d i) + 1) : ℝ))^(1 / n : ℝ)) := by
    contrapose! h_prod_ineq;
    refine lt_of_lt_of_le ?_ h_prod_ineq2;
    convert pow_lt_pow_left₀ h_prod_ineq ( mul_nonneg ( by positivity ) <| Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( add_nonneg zero_le_one <| mul_nonneg ( Nat.cast_nonneg _ ) <| hw _ ) _ ) ( by positivity : n ≠ 0 ) using 1 ; norm_num [ Finset.prod_pow, mul_pow ] ; ring;
    exact Or.inl ( by rw [ ← Finset.prod_pow ] ; exact Finset.prod_congr rfl fun _ _ => by rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by nlinarith only [ hw ‹_› ] ) ] ; ring );
  convert h_combined using 2;
  rw [ ← Real.finset_prod_rpow ];
  · rw [ ← Real.finset_prod_rpow ];
    · exact congrArg _ ( Finset.prod_congr rfl fun _ _ => by rw [ ← Real.rpow_mul ( by nlinarith only [ hw ‹_› ] ) ] ; rw [ ← Real.rpow_mul ( by nlinarith only [ hw ‹_› ] ) ] ; ring );
    · exact fun i _ => Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( by positivity ) ( hw i ) ) ) _;
  · exact fun i _ => Real.rpow_nonneg ( add_nonneg zero_le_one ( mul_nonneg ( by positivity ) ( hw i ) ) ) _

/-
Recurrence relation for the multivariate independence polynomial: Z_G(w) = Z_{G-v}(w) + w(v) * Z_{G-(N(v)∪{v})}(w).
-/
lemma indep_poly_recurrence {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj]
    (w : V → ℝ) (v : V) :
    multivariateIndependencePolynomial G w =
    multivariateIndependencePolynomial (G.induce {x | x ≠ v}) (w ∘ Subtype.val) +
    w v * multivariateIndependencePolynomial (G.induce {x | x ≠ v ∧ ¬G.Adj v x}) (w ∘ Subtype.val) := by
  simp +decide [ multivariateIndependencePolynomial ];
  -- Let's simplify the sum over the independent sets of the induced graph.
  have h_ind : ∑ I ∈ Finset.filter (fun I => G.IsIndepSet I) (Finset.powerset (Finset.univ : Finset V)), (∏ v ∈ I, w v) =
    (∑ I ∈ Finset.filter (fun I => G.IsIndepSet I ∧ v ∉ I) (Finset.powerset (Finset.univ : Finset V)), (∏ v ∈ I, w v)) +
    (∑ I ∈ Finset.filter (fun I => G.IsIndepSet I ∧ v ∈ I) (Finset.powerset (Finset.univ : Finset V)), (∏ v ∈ I, w v)) := by
      rw [ ← Finset.sum_union ];
      · congr with I ; by_cases hv : v ∈ I <;> aesop;
      · exact Finset.disjoint_filter.mpr ( by aesop );
  convert h_ind using 1;
  · refine' Finset.sum_bij ( fun I _ => I ) _ _ _ _ <;> simp +decide;
    · exact fun I hI => Finset.mem_filter.mp hI |>.2;
    · exact fun a ha => Finset.mem_filter.mpr ⟨ Finset.mem_powerset.mpr ( Finset.subset_univ _ ), ha ⟩;
  · refine' congrArg₂ ( · + · ) _ _;
    · refine' Finset.sum_bij ( fun I _ => I.image Subtype.val ) _ _ _ _ <;> simp +decide [ Finset.mem_powerset, SimpleGraph.isIndepSet_iff ];
      · intro I hI
        simp [indepSets] at hI;
        refine' ⟨ ⟨ I.image Subtype.val, _ ⟩, _ ⟩ <;> simp_all +decide [ Set.Pairwise, Set.ext_iff ];
      · simp +contextual [ Finset.ext_iff, Set.ext_iff ];
        intro a₁ ha₁ a₂ ha₂ h a ha; specialize h a; aesop;
      · intro a ha hv
        refine' ⟨ Finset.filter ( fun x => x.val ∈ a ) Finset.univ, _, _ ⟩
        · simp +decide [ indepSets, SimpleGraph.IsIndepSet, Finset.mem_filter ]
          intro x hx y hy hxy
          have hx_in_a : x.val ∈ a := by aesop
          have hy_in_a : y.val ∈ a := by aesop
          have hxney: x.val ≠ y.val := by aesop
          exact ha hx_in_a hy_in_a hxney
        · simp +decide [ indepSets, SimpleGraph.IsIndepSet ]
          aesop
    · simp +decide [ Finset.mul_sum _ _ _, Finset.sum_filter ];
      rw [ ← Finset.sum_filter ];
      refine' Finset.sum_bij ( fun I hI => Insert.insert v ( Finset.image ( fun x : { x // ¬x = v ∧ ¬G.Adj v x } => x.val ) I ) ) _ _ _ _ <;> simp +decide [ Finset.prod_insert, Finset.mem_image ];
      · simp +decide [ SimpleGraph.IsIndepSet, Set.Pairwise ];
        simp +decide [ indepSets, SimpleGraph.IsIndepSet ];
        simp +contextual [ SimpleGraph.adj_comm ];
        intro a ha x hx hx' hx'' y hy hy' hy'' hxy; have := ha hx'' hy''; simp_all +decide [ SimpleGraph.adj_comm ] ;
      · simp +decide [ Finset.ext_iff, Set.ext_iff ];
        intro a₁ ha₁ a₂ ha₂ h a ha₁' ha₂'; specialize h a; aesop;
      · intro b hb hv
        use Finset.filter (fun x => x.val ∈ b ∧ x.val ≠ v ∧ ¬G.Adj v x.val) (Finset.univ : Finset { x : V // ¬x = v ∧ ¬G.Adj v x });
        refine' ⟨ _, _ ⟩;
        · simp +decide [ indepSets, SimpleGraph.IsIndepSet ];
          intro x hx y hy hxy; have := hb ( show ( x : V ) ∈ b from by aesop ) ( show ( y : V ) ∈ b from by aesop ) ; aesop;
        · ext x; by_cases hx : x = v <;> simp +decide [ hx, hv ] ;
          exact fun hx' => hb hv hx' |> fun h => by tauto;

/-
The term $(1+(d+1)w)^{1/(d+1)}$ is non-increasing in $d$.
-/
lemma term_monotonicity (d d' : ℕ) (w : ℝ) (hw : 0 ≤ w) (h : d ≤ d') :
    (1 + (d + 1 : ℝ) * w) ^ (1 / (d + 1 : ℝ)) ≥ (1 + (d' + 1 : ℝ) * w) ^ (1 / (d' + 1 : ℝ)) := by
  -- Let $f(x) = (1+xw)^{1/x}$. We show $f(x)$ is decreasing for $x > 0$.
  have h_decreasing : ∀ x y : ℝ, 0 < x → x < y → (1 + x * w) ^ (1 / x : ℝ) ≥ (1 + y * w) ^ (1 / y : ℝ) := by
    -- Taking the natural logarithm of both sides, we need to show that $\frac{\ln(1+yw)}{y} \leq \frac{\ln(1+xw)}{x}$ for $0 < x < y$.
    suffices h_ln : ∀ x y : ℝ, 0 < x → x < y → Real.log (1 + y * w) / y ≤ Real.log (1 + x * w) / x by
      exact fun x y hx hy => by rw [ Real.rpow_def_of_pos ( by nlinarith ), Real.rpow_def_of_pos ( by nlinarith ) ] ; simpa [ div_eq_mul_inv ] using Real.exp_le_exp.mpr ( h_ln x y hx hy ) ;
    -- Let's consider the function $f(x) = \frac{\ln(1 + xw)}{x}$ and show that it is decreasing for $x > 0$.
    have h_decreasing : ∀ x y : ℝ, 0 < x → x < y → deriv (fun x => Real.log (1 + x * w) / x) x ≤ 0 := by
      intro x y hx hy; norm_num [ show 1 + x * w ≠ 0 by nlinarith, hx.ne' ] ; ring_nf; norm_num; (
                                    exact mul_le_mul_of_nonneg_right ( by nlinarith [ inv_mul_cancel_left₀ ( by nlinarith : ( 1 + w * x ) ≠ 0 ) ( w * x ), Real.log_inv ( 1 + w * x ), Real.log_le_sub_one_of_pos ( inv_pos.mpr ( by nlinarith : 0 < 1 + w * x ) ), mul_inv_cancel₀ ( by nlinarith : ( 1 + w * x ) ≠ 0 ) ] ) ( by positivity ));
    -- By the Mean Value Theorem, there exists some $c \in (x, y)$ such that $f'(c) = \frac{f(y) - f(x)}{y - x}$.
    intros x y hx hy
    obtain ⟨c, hc⟩ : ∃ c ∈ Set.Ioo x y, deriv (fun x => Real.log (1 + x * w) / x) c = (Real.log (1 + y * w) / y - Real.log (1 + x * w) / x) / (y - x) := by
      apply_rules [ exists_deriv_eq_slope ];
      · exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.div ( ContinuousAt.log ( continuousAt_const.add ( continuousAt_id.mul continuousAt_const ) ) ( by nlinarith [ hx.1 ] ) ) continuousAt_id ( by linarith [ hx.1 ] );
      · exact DifferentiableOn.div ( DifferentiableOn.log ( DifferentiableOn.add ( differentiableOn_const _ ) ( differentiableOn_id.mul_const _ ) ) ( by intro u hu; nlinarith [ hu.1 ] ) ) differentiableOn_id ( by intro u hu; linarith [ hu.1 ] );
    have := h_decreasing c y ( by linarith [ hc.1.1 ] ) hc.1.2; rw [ hc.2, div_le_iff₀ ] at this <;> linarith;
  cases eq_or_lt_of_le h <;> [ aesop; exact h_decreasing _ _ ( by positivity ) ( by norm_cast; linarith ) ]

/-
A version of `key_tech_ineq` for `Finset`s.
-/
lemma key_tech_ineq_finset {V : Type*} [DecidableEq V] (S : Finset V) (n : ℕ) (hn : S.card = n) (hn_ge_1 : n ≥ 1)
    (d : V → ℕ) (hd : ∀ i ∈ S, 1 ≤ d i ∧ d i ≤ n)
    (w : V → ℝ) (hw : ∀ i ∈ S, 0 ≤ w i) (w0 : ℝ) (hw0 : 0 ≤ w0) :
    ∏ i ∈ S, (1 + (d i : ℝ) * w i) ^ (1 / (d i : ℝ)) + w0 ≥
    ((n + 1 : ℝ) * w0 + 1) ^ (1 / (n + 1 : ℝ)) * ∏ i ∈ S, (1 + ((d i : ℝ) + 1) * w i) ^ (1 / ((d i : ℝ) + 1)) := by
  -- Let $e : Fin n ≃ S$ be an equivalence.
  obtain ⟨e, he⟩ : ∃ e : Fin n ≃ S, True := by
    exact ⟨ ( Fintype.equivOfCardEq <| by simp +decide [ hn ] ), trivial ⟩;
  convert key_tech_ineq n hn_ge_1 ( fun i => d ( e i ) ) ( fun i => ?_ ) ( fun i => w ( e i ) ) ( fun i => ?_ ) w0 hw0 using 1;
  · rw [ ← Finset.prod_coe_sort ];
    conv_lhs => rw [ ← Equiv.prod_comp e ] ;
  · refine' congr rfl ( Finset.prod_bij ( fun i hi => Classical.choose ( e.surjective ⟨ i, hi ⟩ ) ) _ _ _ _ ) <;> simp +decide [ Classical.choose_spec ( e.surjective _ ) ];
    · intro a₁ ha₁ a₂ ha₂ h; have := Classical.choose_spec ( e.surjective ⟨ a₁, ha₁ ⟩ ) ; have := Classical.choose_spec ( e.surjective ⟨ a₂, ha₂ ⟩ ) ; aesop;
    · intro b; use e b; have := Classical.choose_spec ( e.surjective ( e b ) ) ; aesop;
  · exact hd _ ( e i |>.2 );
  · exact hw _ ( e i |>.2 )

/-
Definition of the lower bound term for the independence polynomial.
-/
noncomputable def indepPolyLowerBound {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] (w : V → ℝ) : ℝ :=
  ∏ v : V, ((G.degree v + 1 : ℝ) * w v + 1) ^ (1 / (G.degree v + 1 : ℝ))

/-
The degree of a vertex u in G - {v} is deg(u) - 1 if u is adjacent to v, and deg(u) otherwise.
-/
lemma degree_delete_eq {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] (v : V) (u : V) (h : u ≠ v) :
    (G.induce {x | x ≠ v}).degree ⟨u, h⟩ = if G.Adj v u then G.degree u - 1 else G.degree u := by
  simp +decide [ SimpleGraph.degree, SimpleGraph.neighborFinset_def ];
  split_ifs with h';
  · rw [ ← Finset.card_erase_of_mem ( Finset.mem_filter.mpr ⟨ Finset.mem_univ _, h'.symm ⟩ ) ];
    refine' Finset.card_bij ( fun x hx => x ) _ _ _ <;> aesop;
  · rw [ Finset.card_filter, Finset.card_filter ];
    rw [ ← Finset.sum_subset ( Finset.subset_univ ( Finset.image ( fun x : { x : V // ¬x = v } => ( x : V ) ) Finset.univ ) ) ];
    · rw [ Finset.sum_image ] ; aesop;
    · simp +contextual;
      rwa [ SimpleGraph.adj_comm ]

/-
The degree of a vertex in an induced subgraph is at most its degree in the original graph.
-/
lemma degree_induce_le {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] (s : Set V) [DecidablePred (· ∈ s)] (v : s) :
    (G.induce s).degree v ≤ G.degree v := by
  simp +decide [ SimpleGraph.degree, SimpleGraph.neighborFinset ];
  convert Set.ncard_le_ncard ( show ( Set.image ( fun x : s => x.val ) ( { x : s | G.Adj v x } ) ) ⊆ ( Set.image ( fun x : V => x ) ( { x : V | G.Adj v x } ) ) from ?_ ) using 1 <;> simp +decide [ Set.ncard_eq_toFinset_card' ];
  rw [ Finset.card_image_of_injective _ Subtype.coe_injective ]

/-
The algebraic step for the lower bound proof, applying the key inequality to the neighbors of a max degree vertex.
-/
lemma indep_poly_lower_bound_step {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj]
    (w : V → ℝ) (hw : ∀ v, 0 ≤ w v) (v : V) (h_max : ∀ u, G.degree u ≤ G.degree v) :
    (∏ u ∈ G.neighborFinset v, ((G.degree u : ℝ) * w u + 1) ^ (1 / (G.degree u : ℝ))) + w v ≥
    ((G.degree v + 1 : ℝ) * w v + 1) ^ (1 / (G.degree v + 1 : ℝ)) * ∏ u ∈ G.neighborFinset v, ((G.degree u + 1 : ℝ) * w u + 1) ^ (1 / (G.degree u + 1 : ℝ)) := by
  by_cases hd : G.degree v = 0 <;> simp_all +decide [ SimpleGraph.degree, SimpleGraph.neighborFinset ];
  · simp +decide [ SimpleGraph.neighborSet, h_max ];
    linarith;
  · have := @key_tech_ineq_finset V _ ( G.neighborSet v |> Set.toFinset ) ( Fintype.card ( { x : V | G.Adj v x } ) ) ?_ ?_ ( fun u => Fintype.card ( { x : V | G.Adj u x } ) ) ?_ ( fun u => w u ) ?_ ( w v ) ?_ <;> simp_all +decide [ SimpleGraph.neighborFinset ];
    · convert this using 3 <;> simp +decide [ add_comm, Fintype.card_subtype ];
    · exact?;
    · exact Fintype.card_pos_iff.mpr ⟨ ⟨ hd.choose, hd.choose_spec ⟩ ⟩;
    · simp_all +decide [ Fintype.card_subtype ];
      exact fun u hu => ⟨ v, by simpa [ SimpleGraph.adj_comm ] using hu ⟩

/-
Splitting the lower bound product for $G-v$ into neighbors and non-neighbors.
-/
lemma prod_G_minus_v_eq {V : Type*} [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj]
    (w : V → ℝ) (v : V) :
    indepPolyLowerBound (G.induce {x | x ≠ v}) (w ∘ Subtype.val) =
    (∏ u ∈ G.neighborFinset v, ((G.degree u : ℝ) * w u + 1) ^ (1 / (G.degree u : ℝ))) *
    (∏ u ∈ Finset.univ.filter (fun x => x ≠ v ∧ ¬G.Adj v x), ((G.degree u + 1 : ℝ) * w u + 1) ^ (1 / (G.degree u + 1 : ℝ))) := by
  unfold indepPolyLowerBound;
  -- Apply the degree deletion lemma to each term in the product.
  have h_deg_deletion : ∀ u : {x : V | x ≠ v}, ((SimpleGraph.induce {x | x ≠ v} G).degree u + 1 : ℝ) = if G.Adj v u.val then (G.degree u.val : ℝ) else (G.degree u.val + 1 : ℝ) := by
    intro u
    have h_deg : (SimpleGraph.induce {x | x ≠ v} G).degree u = if G.Adj v u.val then G.degree u.val - 1 else G.degree u.val := by
      convert degree_delete_eq G v u.val u.prop using 1;
    split_ifs at * <;> simp_all +decide;
    rw [ Nat.cast_sub ] <;> norm_num ; exact G.degree_pos_iff_exists_adj _ |>.2 ⟨ v, by tauto ⟩;
  simp_all +decide [ Finset.prod_ite, Finset.filter_congr ];
  rw [ ← Finset.prod_filter_mul_prod_filter_not ( Finset.univ : Finset { x : V // ¬x = v } ) fun x => G.Adj v x ];
  refine' congrArg₂ _ _ _;
  · refine' Finset.prod_bij ( fun x hx => x ) _ _ _ _ <;> aesop;
  · refine' Finset.prod_bij ( fun x hx => x ) _ _ _ _ <;> aesop
